#
# docker build -t mobiledgex/crmserver -f Dockerfile.crmserver .
# docker run -it --rm mobiledgex/crmserver
# 

FROM golang:latest AS build

WORKDIR /go/src/github.com/mobiledgex/edge-cloud
COPY . .

RUN go clean ./...
RUN go get -d -v ./...
RUN go install -v ./...

ENTRYPOINT [ "/go/bin/crmserver" ]
