apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5tb2JpbGVkZ2V4Lm5ldDo1MDAwL3YyLyI6eyJ1c2VybmFtZSI6Im1vYmlsZWRnZXgiLCJwYXNzd29yZCI6InNhbmRoaWxsIiwiZW1haWwiOiJqaW0ubW9ycmlzQG1vYmlsZWRnZXguY29tIiwiYXV0aCI6ImJXOWlhV3hsWkdkbGVEcHpZVzVrYUdsc2JBPT0ifX19
kind: Secret
metadata:
  name: mexregistrysecret
  namespace: default
type: kubernetes.io/dockerconfigjson
