// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: debug.proto

/*
Package log is a generated protocol buffer package.

It is generated from these files:
	debug.proto

It has these top-level messages:
*/
package log

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

import "github.com/mobiledgex/edge-cloud/util"
import "errors"
import "strconv"
import "encoding/json"
import reflect "reflect"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type DebugLevel int32

const (
	DebugLevel_etcd    DebugLevel = 0
	DebugLevel_api     DebugLevel = 1
	DebugLevel_notify  DebugLevel = 2
	DebugLevel_dmedb   DebugLevel = 3
	DebugLevel_dmereq  DebugLevel = 4
	DebugLevel_locapi  DebugLevel = 5
	DebugLevel_mexos   DebugLevel = 6
	DebugLevel_metrics DebugLevel = 7
	DebugLevel_upgrade DebugLevel = 8
	DebugLevel_info    DebugLevel = 9
	DebugLevel_sampled DebugLevel = 10
	DebugLevel_infra   DebugLevel = 11
)

var DebugLevel_name = map[int32]string{
	0:  "etcd",
	1:  "api",
	2:  "notify",
	3:  "dmedb",
	4:  "dmereq",
	5:  "locapi",
	6:  "mexos",
	7:  "metrics",
	8:  "upgrade",
	9:  "info",
	10: "sampled",
	11: "infra",
}
var DebugLevel_value = map[string]int32{
	"etcd":    0,
	"api":     1,
	"notify":  2,
	"dmedb":   3,
	"dmereq":  4,
	"locapi":  5,
	"mexos":   6,
	"metrics": 7,
	"upgrade": 8,
	"info":    9,
	"sampled": 10,
	"infra":   11,
}

func (x DebugLevel) String() string {
	return proto.EnumName(DebugLevel_name, int32(x))
}
func (DebugLevel) EnumDescriptor() ([]byte, []int) { return fileDescriptorDebug, []int{0} }

func init() {
	proto.RegisterEnum("log.DebugLevel", DebugLevel_name, DebugLevel_value)
}

var DebugLevelStrings = []string{
	"etcd",
	"api",
	"notify",
	"dmedb",
	"dmereq",
	"locapi",
	"mexos",
	"metrics",
	"upgrade",
	"info",
	"sampled",
	"infra",
}

const (
	DebugLevelEtcd    uint64 = 1 << 0
	DebugLevelApi     uint64 = 1 << 1
	DebugLevelNotify  uint64 = 1 << 2
	DebugLevelDmedb   uint64 = 1 << 3
	DebugLevelDmereq  uint64 = 1 << 4
	DebugLevelLocapi  uint64 = 1 << 5
	DebugLevelMexos   uint64 = 1 << 6
	DebugLevelMetrics uint64 = 1 << 7
	DebugLevelUpgrade uint64 = 1 << 8
	DebugLevelInfo    uint64 = 1 << 9
	DebugLevelSampled uint64 = 1 << 10
	DebugLevelInfra   uint64 = 1 << 11
)

var DebugLevel_CamelName = map[int32]string{
	// etcd -> Etcd
	0: "Etcd",
	// api -> Api
	1: "Api",
	// notify -> Notify
	2: "Notify",
	// dmedb -> Dmedb
	3: "Dmedb",
	// dmereq -> Dmereq
	4: "Dmereq",
	// locapi -> Locapi
	5: "Locapi",
	// mexos -> Mexos
	6: "Mexos",
	// metrics -> Metrics
	7: "Metrics",
	// upgrade -> Upgrade
	8: "Upgrade",
	// info -> Info
	9: "Info",
	// sampled -> Sampled
	10: "Sampled",
	// infra -> Infra
	11: "Infra",
}
var DebugLevel_CamelValue = map[string]int32{
	"Etcd":    0,
	"Api":     1,
	"Notify":  2,
	"Dmedb":   3,
	"Dmereq":  4,
	"Locapi":  5,
	"Mexos":   6,
	"Metrics": 7,
	"Upgrade": 8,
	"Info":    9,
	"Sampled": 10,
	"Infra":   11,
}

func (e *DebugLevel) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var str string
	err := unmarshal(&str)
	if err != nil {
		return err
	}
	val, ok := DebugLevel_CamelValue[util.CamelCase(str)]
	if !ok {
		// may be enum value instead of string
		ival, err := strconv.Atoi(str)
		val = int32(ival)
		if err == nil {
			_, ok = DebugLevel_CamelName[val]
		}
	}
	if !ok {
		return errors.New(fmt.Sprintf("No enum value for %s", str))
	}
	*e = DebugLevel(val)
	return nil
}

func (e DebugLevel) MarshalYAML() (interface{}, error) {
	return proto.EnumName(DebugLevel_CamelName, int32(e)), nil
}

// custom JSON encoding/decoding
func (e *DebugLevel) UnmarshalJSON(b []byte) error {
	var str string
	err := json.Unmarshal(b, &str)
	if err == nil {
		val, ok := DebugLevel_CamelValue[util.CamelCase(str)]
		if !ok {
			// may be int value instead of enum name
			ival, err := strconv.Atoi(str)
			val = int32(ival)
			if err == nil {
				_, ok = DebugLevel_CamelName[val]
			}
		}
		if !ok {
			return errors.New(fmt.Sprintf("No enum value for %s", str))
		}
		*e = DebugLevel(val)
		return nil
	}
	var val int32
	err = json.Unmarshal(b, &val)
	if err == nil {
		*e = DebugLevel(val)
		return nil
	}
	return fmt.Errorf("No enum value for %v", b)
}

type MatchOptions struct {
	// Filter will ignore 0 or nil fields on the passed in object
	Filter bool
	// IgnoreBackend will ignore fields that were marked backend in .proto
	IgnoreBackend bool
	// Sort repeated (arrays) of Key objects so matching does not
	// fail due to order.
	SortArrayedKeys bool
}

type MatchOpt func(*MatchOptions)

func MatchFilter() MatchOpt {
	return func(opts *MatchOptions) {
		opts.Filter = true
	}
}

func MatchIgnoreBackend() MatchOpt {
	return func(opts *MatchOptions) {
		opts.IgnoreBackend = true
	}
}

func MatchSortArrayedKeys() MatchOpt {
	return func(opts *MatchOptions) {
		opts.SortArrayedKeys = true
	}
}

func applyMatchOptions(opts *MatchOptions, args ...MatchOpt) {
	for _, f := range args {
		f(opts)
	}
}

// DecodeHook for use with the mapstructure package.
// Allows decoding to handle protobuf enums that are
// represented as strings.
func EnumDecodeHook(from, to reflect.Type, data interface{}) (interface{}, error) {
	if from.Kind() != reflect.String {
		return data, nil
	}
	switch to {
	case reflect.TypeOf(DebugLevel(0)):
		if en, ok := DebugLevel_CamelValue[util.CamelCase(data.(string))]; ok {
			return en, nil
		}
	}
	return data, nil
}

func init() { proto.RegisterFile("debug.proto", fileDescriptorDebug) }

var fileDescriptorDebug = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x1c, 0x8e, 0xbd, 0x6d, 0xc3, 0x30,
	0x10, 0x85, 0xc5, 0xe8, 0xff, 0xd4, 0x1c, 0x38, 0x00, 0x07, 0x48, 0x91, 0x26, 0x1b, 0x04, 0x29,
	0xb3, 0x04, 0x25, 0x9e, 0x04, 0x02, 0xa4, 0xc8, 0x50, 0x54, 0x10, 0x0f, 0xe2, 0x9d, 0x54, 0x7a,
	0x04, 0x5b, 0x93, 0x18, 0xe7, 0xee, 0xee, 0xc3, 0xf7, 0xf0, 0x1e, 0x0c, 0x86, 0xc6, 0x7d, 0xf9,
	0x88, 0x29, 0xe4, 0x20, 0x4b, 0x17, 0x96, 0xf7, 0xab, 0x00, 0xf8, 0x66, 0xf8, 0x43, 0x7f, 0xe4,
	0x64, 0x07, 0x15, 0xe5, 0xc9, 0x60, 0x21, 0x5b, 0x28, 0x75, 0xb4, 0x28, 0x24, 0x40, 0xb3, 0x86,
	0x6c, 0xe7, 0x0b, 0xbe, 0xc9, 0x1e, 0x6a, 0xe3, 0xc9, 0x8c, 0x58, 0x32, 0x36, 0x9e, 0x12, 0xfd,
	0x62, 0xc5, 0xb7, 0x0b, 0x13, 0xeb, 0x35, 0x2b, 0x9e, 0xfe, 0xc3, 0x86, 0x8d, 0x1c, 0xa0, 0xf5,
	0x94, 0x93, 0x9d, 0x36, 0x6c, 0xf9, 0xd9, 0xe3, 0x92, 0xb4, 0x21, 0xec, 0xb8, 0xc6, 0xae, 0x73,
	0xc0, 0x9e, 0xf1, 0xa6, 0x7d, 0x74, 0x64, 0x10, 0x38, 0x6b, 0xd7, 0x39, 0x69, 0x1c, 0xbe, 0xf0,
	0x78, 0xa8, 0xe2, 0x38, 0x95, 0xb8, 0x9d, 0x4a, 0xdc, 0x4f, 0x25, 0xc6, 0xe6, 0xb5, 0xfa, 0xf3,
	0x19, 0x00, 0x00, 0xff, 0xff, 0x16, 0x52, 0x37, 0x55, 0xc4, 0x00, 0x00, 0x00,
}
