apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-svc
  labels:
    app: cluster-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-svc
  template:
    metadata:
      labels:
        app: cluster-svc
    spec:
      containers:
      - name: cluster-svc
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:latest
        imagePullPolicy: Always
        command:
         - "cluster-svc"
         - "--notifyAddrs"
         - "controller:37001"
         - "--ctrlAddrs"
         - "controller:55001"
         - "--d"
         - "mexos,notify"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--influxdb"
         - "monitoring-influxdb:8086"
      imagePullSecrets:
       - name: mexreg-secret 

