apiVersion: apps/v1
kind: Deployment
metadata:
  name: monitor
  labels:
    app: monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monitor
  template:
    metadata:
      labels:
        app: monitor
    spec:
      containers:
      - name: monitor
        image: registry.mobiledgex.net:5000/mobiledgex/monitor:latest
         
      imagePullSecrets:
       - name: mexreg-secret 

