apiVersion: v1
kind: Service
metadata:
  labels:
    app: locsim
  name: locsim
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: locsim
    port: 8888
    protocol: TCP
  selector:
    app: locsim
  sessionAffinity: None
  type: NodePort
