apiVersion: v1
kind: Service
metadata:
  labels:
    app: mc
  name: mc
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
   - port: 9900
     name: api
     protocol: TCP
     targetPort: 9900
   - port: 9389
     name: ldap
     protocol: TCP
     targetPort: 9389
  selector:
    app: mc
  sessionAffinity: None
  type: LoadBalancer
