apiVersion: v1
kind: Service
metadata:
  labels:
    app: monitor
  name: monitor
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
   - port: 80
     name: http
     protocol: TCP
     targetPort: 8080
  selector:
    app: monitor
  sessionAffinity: None
  type: LoadBalancer
