apiVersion: v1
kind: Service
metadata:
  labels:
    app: toksrv
  name: toksrv
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
   - port: 9999
     protocol: TCP
     targetPort: 9999
  selector:
    app: toksrv
  sessionAffinity: None
  type: LoadBalancer
