apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm-uscentral
  labels:
    app: crm-uscentral
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crm-uscentral
  template:
    metadata:
      labels:
        app: crm-uscentral
    spec:
      hostAliases:
      containers:
      - name: crm-uscentral
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:jlm0211
        imagePullPolicy: Always
        command:
         - crmserver
        args:
         - "--apiAddr"
         - "0.0.0.0:55091"
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"azure\"},\"name\":\"uscentral-mexdemo\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--d"
         - "mexos"
        env:
         - name: PATH
           value: /tmp/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin 
         - name: MEXENV_URL
           value: https://vault.mobiledgex.net/v1/secret/data/cloudlet/openstack/mexenv.json
         - name: CLOUDLET_KIND
           value: azure
         - name: MEX_AZURE_LOCATION
           value: centralus


      imagePullSecrets:
       - name: mexreg-secret

