apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmbonn
  labels:
    app: crmbonn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmbonn
  template:
    metadata:
      labels:
        app: crmbonn
    spec:
      hostAliases:
       - ip: "37.50.143.121"
         hostnames:
         - "bonnedgecloud.telekom.de"
      containers:
      - name: crmbonn
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:latest
        imagePullPolicy: Always
        env:
         - name: MEX_CF_USER
           value: mobiledgex.ops@mobiledgex.com
         - name: MEX_CF_KEY
           value: 60632181cb3b7419304ffa820b2d99e292092
         - name: MEX_SSH_KEY
           value: id_rsa_mobiledgex
         - name: MEX_DOCKER_REG_PASS
           value: sandhill
         - name: MEX_DIR
           value: /root/.mobiledgex
         - name: OS_AUTH_URL
           value: https://bonnedgecloud.telekom.de:5000/v2.0
         - name: OS_CACERT
           value: /root/.mobiledgex/bonnedgecloudtelekomde.crt
         - name: OS_USERNAME
           value: mexadmin
         - name: OS_PASSWORD
           value: kj&shy2%Jt5F4$Wz
         - name: OS_REGION_NAME
           value: RegionOne
         - name: OS_TENANT_NAME
           value: mex
        command:
         - crmserver
        args:
         - "--apiAddr"
         - "0.0.0.0:55091"
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"TDG\"},\"name\":\"bonndemocloudlet\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--d"
         - "mexos"

      imagePullSecrets:
       - name: mexreg-secret

