// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: client.proto

package edgeproto

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/mobiledgex/edge-cloud/protogen"
import distributed_match_engine "github.com/mobiledgex/edge-cloud/d-match-engine/dme-proto"
import _ "github.com/gogo/protobuf/gogoproto"

import context "golang.org/x/net/context"
import grpc "google.golang.org/grpc"

import "github.com/mobiledgex/edge-cloud/util"
import strings "strings"
import "errors"
import "strconv"
import "encoding/json"
import "github.com/google/go-cmp/cmp"
import "github.com/google/go-cmp/cmp/cmpopts"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type AppInstClient_FindStatus int32

const (
	AppInstClient_FIND_UNKNOWN  AppInstClient_FindStatus = 0
	AppInstClient_FIND_FOUND    AppInstClient_FindStatus = 1
	AppInstClient_FIND_NOTFOUND AppInstClient_FindStatus = 2
)

var AppInstClient_FindStatus_name = map[int32]string{
	0: "FIND_UNKNOWN",
	1: "FIND_FOUND",
	2: "FIND_NOTFOUND",
}
var AppInstClient_FindStatus_value = map[string]int32{
	"FIND_UNKNOWN":  0,
	"FIND_FOUND":    1,
	"FIND_NOTFOUND": 2,
}

func (x AppInstClient_FindStatus) String() string {
	return proto.EnumName(AppInstClient_FindStatus_name, int32(x))
}
func (AppInstClient_FindStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptorClient, []int{1, 0}
}

// AppKey uniquely identifies an App
type AppInstClientKey struct {
	// AppInst Key
	AppInstKey *AppInstKey `protobuf:"bytes,1,opt,name=app_inst_key,json=appInstKey" json:"app_inst_key,omitempty"`
	// App name
	Uuid string `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (m *AppInstClientKey) Reset()                    { *m = AppInstClientKey{} }
func (m *AppInstClientKey) String() string            { return proto.CompactTextString(m) }
func (*AppInstClientKey) ProtoMessage()               {}
func (*AppInstClientKey) Descriptor() ([]byte, []int) { return fileDescriptorClient, []int{0} }

// Client is an AppInst client that called FindCloudlet DME Api
type AppInstClient struct {
	// Fields are used for the Update API to specify which fields to apply
	Fields []string `protobuf:"bytes,1,rep,name=fields" json:"fields,omitempty"`
	// Unique identifier key
	ClientKey AppInstClientKey `protobuf:"bytes,2,opt,name=client_key,json=clientKey" json:"client_key"`
	// Location of the Client
	Location distributed_match_engine.Loc `protobuf:"bytes,3,opt,name=location" json:"location"`
	// Id of client assigned by server (internal use only)
	NotifyId int64 `protobuf:"varint,5,opt,name=notify_id,json=notifyId,proto3" json:"notify_id,omitempty"`
	// Status return
	Status AppInstClient_FindStatus `protobuf:"varint,6,opt,name=status,proto3,enum=edgeproto.AppInstClient_FindStatus" json:"status,omitempty"`
}

func (m *AppInstClient) Reset()                    { *m = AppInstClient{} }
func (m *AppInstClient) String() string            { return proto.CompactTextString(m) }
func (*AppInstClient) ProtoMessage()               {}
func (*AppInstClient) Descriptor() ([]byte, []int) { return fileDescriptorClient, []int{1} }

func init() {
	proto.RegisterType((*AppInstClientKey)(nil), "edgeproto.AppInstClientKey")
	proto.RegisterType((*AppInstClient)(nil), "edgeproto.AppInstClient")
	proto.RegisterEnum("edgeproto.AppInstClient_FindStatus", AppInstClient_FindStatus_name, AppInstClient_FindStatus_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AppInstClientApi service

type AppInstClientApiClient interface {
	// Show application instance clients.
	ShowAppInstClient(ctx context.Context, in *AppInstClient, opts ...grpc.CallOption) (AppInstClientApi_ShowAppInstClientClient, error)
}

type appInstClientApiClient struct {
	cc *grpc.ClientConn
}

func NewAppInstClientApiClient(cc *grpc.ClientConn) AppInstClientApiClient {
	return &appInstClientApiClient{cc}
}

func (c *appInstClientApiClient) ShowAppInstClient(ctx context.Context, in *AppInstClient, opts ...grpc.CallOption) (AppInstClientApi_ShowAppInstClientClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_AppInstClientApi_serviceDesc.Streams[0], c.cc, "/edgeproto.AppInstClientApi/ShowAppInstClient", opts...)
	if err != nil {
		return nil, err
	}
	x := &appInstClientApiShowAppInstClientClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type AppInstClientApi_ShowAppInstClientClient interface {
	Recv() (*AppInstClient, error)
	grpc.ClientStream
}

type appInstClientApiShowAppInstClientClient struct {
	grpc.ClientStream
}

func (x *appInstClientApiShowAppInstClientClient) Recv() (*AppInstClient, error) {
	m := new(AppInstClient)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for AppInstClientApi service

type AppInstClientApiServer interface {
	// Show application instance clients.
	ShowAppInstClient(*AppInstClient, AppInstClientApi_ShowAppInstClientServer) error
}

func RegisterAppInstClientApiServer(s *grpc.Server, srv AppInstClientApiServer) {
	s.RegisterService(&_AppInstClientApi_serviceDesc, srv)
}

func _AppInstClientApi_ShowAppInstClient_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(AppInstClient)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AppInstClientApiServer).ShowAppInstClient(m, &appInstClientApiShowAppInstClientServer{stream})
}

type AppInstClientApi_ShowAppInstClientServer interface {
	Send(*AppInstClient) error
	grpc.ServerStream
}

type appInstClientApiShowAppInstClientServer struct {
	grpc.ServerStream
}

func (x *appInstClientApiShowAppInstClientServer) Send(m *AppInstClient) error {
	return x.ServerStream.SendMsg(m)
}

var _AppInstClientApi_serviceDesc = grpc.ServiceDesc{
	ServiceName: "edgeproto.AppInstClientApi",
	HandlerType: (*AppInstClientApiServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ShowAppInstClient",
			Handler:       _AppInstClientApi_ShowAppInstClient_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "client.proto",
}

func (m *AppInstClientKey) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AppInstClientKey) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.AppInstKey != nil {
		dAtA[i] = 0xa
		i++
		i = encodeVarintClient(dAtA, i, uint64(m.AppInstKey.Size()))
		n1, err := m.AppInstKey.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	if len(m.Uuid) > 0 {
		dAtA[i] = 0x12
		i++
		i = encodeVarintClient(dAtA, i, uint64(len(m.Uuid)))
		i += copy(dAtA[i:], m.Uuid)
	}
	return i, nil
}

func (m *AppInstClient) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AppInstClient) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Fields) > 0 {
		for _, s := range m.Fields {
			dAtA[i] = 0xa
			i++
			l = len(s)
			for l >= 1<<7 {
				dAtA[i] = uint8(uint64(l)&0x7f | 0x80)
				l >>= 7
				i++
			}
			dAtA[i] = uint8(l)
			i++
			i += copy(dAtA[i:], s)
		}
	}
	dAtA[i] = 0x12
	i++
	i = encodeVarintClient(dAtA, i, uint64(m.ClientKey.Size()))
	n2, err := m.ClientKey.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n2
	dAtA[i] = 0x1a
	i++
	i = encodeVarintClient(dAtA, i, uint64(m.Location.Size()))
	n3, err := m.Location.MarshalTo(dAtA[i:])
	if err != nil {
		return 0, err
	}
	i += n3
	if m.NotifyId != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintClient(dAtA, i, uint64(m.NotifyId))
	}
	if m.Status != 0 {
		dAtA[i] = 0x30
		i++
		i = encodeVarintClient(dAtA, i, uint64(m.Status))
	}
	return i, nil
}

func encodeVarintClient(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *AppInstClientKey) CopyInFields(src *AppInstClientKey) int {
	changed := 0
	if src.AppInstKey != nil {
		m.AppInstKey = &AppInstKey{}
		if m.AppInstKey.AppKey.DeveloperKey.Name != src.AppInstKey.AppKey.DeveloperKey.Name {
			m.AppInstKey.AppKey.DeveloperKey.Name = src.AppInstKey.AppKey.DeveloperKey.Name
			changed++
		}
		if m.AppInstKey.AppKey.Name != src.AppInstKey.AppKey.Name {
			m.AppInstKey.AppKey.Name = src.AppInstKey.AppKey.Name
			changed++
		}
		if m.AppInstKey.AppKey.Version != src.AppInstKey.AppKey.Version {
			m.AppInstKey.AppKey.Version = src.AppInstKey.AppKey.Version
			changed++
		}
		if m.AppInstKey.ClusterInstKey.ClusterKey.Name != src.AppInstKey.ClusterInstKey.ClusterKey.Name {
			m.AppInstKey.ClusterInstKey.ClusterKey.Name = src.AppInstKey.ClusterInstKey.ClusterKey.Name
			changed++
		}
		if m.AppInstKey.ClusterInstKey.CloudletKey.OperatorKey.Name != src.AppInstKey.ClusterInstKey.CloudletKey.OperatorKey.Name {
			m.AppInstKey.ClusterInstKey.CloudletKey.OperatorKey.Name = src.AppInstKey.ClusterInstKey.CloudletKey.OperatorKey.Name
			changed++
		}
		if m.AppInstKey.ClusterInstKey.CloudletKey.Name != src.AppInstKey.ClusterInstKey.CloudletKey.Name {
			m.AppInstKey.ClusterInstKey.CloudletKey.Name = src.AppInstKey.ClusterInstKey.CloudletKey.Name
			changed++
		}
		if m.AppInstKey.ClusterInstKey.Developer != src.AppInstKey.ClusterInstKey.Developer {
			m.AppInstKey.ClusterInstKey.Developer = src.AppInstKey.ClusterInstKey.Developer
			changed++
		}
	} else if m.AppInstKey != nil {
		m.AppInstKey = nil
		changed++
	}
	if m.Uuid != src.Uuid {
		m.Uuid = src.Uuid
		changed++
	}
	return changed
}

// Helper method to check that enums have valid values
func (m *AppInstClientKey) ValidateEnums() error {
	if err := m.AppInstKey.ValidateEnums(); err != nil {
		return err
	}
	return nil
}

const AppInstClientFieldClientKey = "2"
const AppInstClientFieldClientKeyAppInstKey = "2.1"
const AppInstClientFieldClientKeyAppInstKeyAppKey = "2.1.1"
const AppInstClientFieldClientKeyAppInstKeyAppKeyDeveloperKey = "2.1.1.1"
const AppInstClientFieldClientKeyAppInstKeyAppKeyDeveloperKeyName = "2.1.1.1.2"
const AppInstClientFieldClientKeyAppInstKeyAppKeyName = "2.1.1.2"
const AppInstClientFieldClientKeyAppInstKeyAppKeyVersion = "2.1.1.3"
const AppInstClientFieldClientKeyAppInstKeyClusterInstKey = "2.1.4"
const AppInstClientFieldClientKeyAppInstKeyClusterInstKeyClusterKey = "2.1.4.1"
const AppInstClientFieldClientKeyAppInstKeyClusterInstKeyClusterKeyName = "2.1.4.1.1"
const AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKey = "2.1.4.2"
const AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKeyOperatorKey = "2.1.4.2.1"
const AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKeyOperatorKeyName = "2.1.4.2.1.1"
const AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKeyName = "2.1.4.2.2"
const AppInstClientFieldClientKeyAppInstKeyClusterInstKeyDeveloper = "2.1.4.3"
const AppInstClientFieldClientKeyUuid = "2.2"
const AppInstClientFieldLocation = "3"
const AppInstClientFieldLocationLatitude = "3.1"
const AppInstClientFieldLocationLongitude = "3.2"
const AppInstClientFieldLocationHorizontalAccuracy = "3.3"
const AppInstClientFieldLocationVerticalAccuracy = "3.4"
const AppInstClientFieldLocationAltitude = "3.5"
const AppInstClientFieldLocationCourse = "3.6"
const AppInstClientFieldLocationSpeed = "3.7"
const AppInstClientFieldLocationTimestamp = "3.8"
const AppInstClientFieldLocationTimestampSeconds = "3.8.1"
const AppInstClientFieldLocationTimestampNanos = "3.8.2"
const AppInstClientFieldNotifyId = "5"
const AppInstClientFieldStatus = "6"

var AppInstClientAllFields = []string{
	AppInstClientFieldClientKeyAppInstKeyAppKeyDeveloperKeyName,
	AppInstClientFieldClientKeyAppInstKeyAppKeyName,
	AppInstClientFieldClientKeyAppInstKeyAppKeyVersion,
	AppInstClientFieldClientKeyAppInstKeyClusterInstKeyClusterKeyName,
	AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKeyOperatorKeyName,
	AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKeyName,
	AppInstClientFieldClientKeyAppInstKeyClusterInstKeyDeveloper,
	AppInstClientFieldClientKeyUuid,
	AppInstClientFieldLocationLatitude,
	AppInstClientFieldLocationLongitude,
	AppInstClientFieldLocationHorizontalAccuracy,
	AppInstClientFieldLocationVerticalAccuracy,
	AppInstClientFieldLocationAltitude,
	AppInstClientFieldLocationCourse,
	AppInstClientFieldLocationSpeed,
	AppInstClientFieldLocationTimestampSeconds,
	AppInstClientFieldLocationTimestampNanos,
	AppInstClientFieldNotifyId,
	AppInstClientFieldStatus,
}

var AppInstClientAllFieldsMap = map[string]struct{}{
	AppInstClientFieldClientKeyAppInstKeyAppKeyDeveloperKeyName:                   struct{}{},
	AppInstClientFieldClientKeyAppInstKeyAppKeyName:                               struct{}{},
	AppInstClientFieldClientKeyAppInstKeyAppKeyVersion:                            struct{}{},
	AppInstClientFieldClientKeyAppInstKeyClusterInstKeyClusterKeyName:             struct{}{},
	AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKeyOperatorKeyName: struct{}{},
	AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKeyName:            struct{}{},
	AppInstClientFieldClientKeyAppInstKeyClusterInstKeyDeveloper:                  struct{}{},
	AppInstClientFieldClientKeyUuid:                                               struct{}{},
	AppInstClientFieldLocationLatitude:                                            struct{}{},
	AppInstClientFieldLocationLongitude:                                           struct{}{},
	AppInstClientFieldLocationHorizontalAccuracy:                                  struct{}{},
	AppInstClientFieldLocationVerticalAccuracy:                                    struct{}{},
	AppInstClientFieldLocationAltitude:                                            struct{}{},
	AppInstClientFieldLocationCourse:                                              struct{}{},
	AppInstClientFieldLocationSpeed:                                               struct{}{},
	AppInstClientFieldLocationTimestampSeconds:                                    struct{}{},
	AppInstClientFieldLocationTimestampNanos:                                      struct{}{},
	AppInstClientFieldNotifyId:                                                    struct{}{},
	AppInstClientFieldStatus:                                                      struct{}{},
}

var AppInstClientAllFieldsStringMap = map[string]string{
	AppInstClientFieldClientKeyAppInstKeyAppKeyDeveloperKeyName:                   "Client Key App Inst Key App Key Developer Key Name",
	AppInstClientFieldClientKeyAppInstKeyAppKeyName:                               "Client Key App Inst Key App Key Name",
	AppInstClientFieldClientKeyAppInstKeyAppKeyVersion:                            "Client Key App Inst Key App Key Version",
	AppInstClientFieldClientKeyAppInstKeyClusterInstKeyClusterKeyName:             "Client Key App Inst Key Cluster Inst Key Cluster Key Name",
	AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKeyOperatorKeyName: "Client Key App Inst Key Cluster Inst Key Cloudlet Key Operator Key Name",
	AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKeyName:            "Client Key App Inst Key Cluster Inst Key Cloudlet Key Name",
	AppInstClientFieldClientKeyAppInstKeyClusterInstKeyDeveloper:                  "Client Key App Inst Key Cluster Inst Key Developer",
	AppInstClientFieldClientKeyUuid:                                               "Client Key Uuid",
	AppInstClientFieldLocationLatitude:                                            "Location Latitude",
	AppInstClientFieldLocationLongitude:                                           "Location Longitude",
	AppInstClientFieldLocationHorizontalAccuracy:                                  "Location Horizontal Accuracy",
	AppInstClientFieldLocationVerticalAccuracy:                                    "Location Vertical Accuracy",
	AppInstClientFieldLocationAltitude:                                            "Location Altitude",
	AppInstClientFieldLocationCourse:                                              "Location Course",
	AppInstClientFieldLocationSpeed:                                               "Location Speed",
	AppInstClientFieldLocationTimestampSeconds:                                    "Location Timestamp Seconds",
	AppInstClientFieldLocationTimestampNanos:                                      "Location Timestamp Nanos",
	AppInstClientFieldNotifyId:                                                    "Notify Id",
	AppInstClientFieldStatus:                                                      "Status",
}

func (m *AppInstClient) IsKeyField(s string) bool {
	return strings.HasPrefix(s, AppInstClientFieldClientKey+".")
}

func (m *AppInstClient) DiffFields(o *AppInstClient, fields map[string]struct{}) {
	if m.ClientKey.AppInstKey != nil && o.ClientKey.AppInstKey != nil {
		if m.ClientKey.AppInstKey.AppKey.DeveloperKey.Name != o.ClientKey.AppInstKey.AppKey.DeveloperKey.Name {
			fields[AppInstClientFieldClientKeyAppInstKeyAppKeyDeveloperKeyName] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKeyAppKeyDeveloperKey] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKeyAppKey] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKey] = struct{}{}
			fields[AppInstClientFieldClientKey] = struct{}{}
		}
		if m.ClientKey.AppInstKey.AppKey.Name != o.ClientKey.AppInstKey.AppKey.Name {
			fields[AppInstClientFieldClientKeyAppInstKeyAppKeyName] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKeyAppKey] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKey] = struct{}{}
			fields[AppInstClientFieldClientKey] = struct{}{}
		}
		if m.ClientKey.AppInstKey.AppKey.Version != o.ClientKey.AppInstKey.AppKey.Version {
			fields[AppInstClientFieldClientKeyAppInstKeyAppKeyVersion] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKeyAppKey] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKey] = struct{}{}
			fields[AppInstClientFieldClientKey] = struct{}{}
		}
		if m.ClientKey.AppInstKey.ClusterInstKey.ClusterKey.Name != o.ClientKey.AppInstKey.ClusterInstKey.ClusterKey.Name {
			fields[AppInstClientFieldClientKeyAppInstKeyClusterInstKeyClusterKeyName] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKeyClusterInstKeyClusterKey] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKeyClusterInstKey] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKey] = struct{}{}
			fields[AppInstClientFieldClientKey] = struct{}{}
		}
		if m.ClientKey.AppInstKey.ClusterInstKey.CloudletKey.OperatorKey.Name != o.ClientKey.AppInstKey.ClusterInstKey.CloudletKey.OperatorKey.Name {
			fields[AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKeyOperatorKeyName] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKeyOperatorKey] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKey] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKeyClusterInstKey] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKey] = struct{}{}
			fields[AppInstClientFieldClientKey] = struct{}{}
		}
		if m.ClientKey.AppInstKey.ClusterInstKey.CloudletKey.Name != o.ClientKey.AppInstKey.ClusterInstKey.CloudletKey.Name {
			fields[AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKeyName] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKeyClusterInstKeyCloudletKey] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKeyClusterInstKey] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKey] = struct{}{}
			fields[AppInstClientFieldClientKey] = struct{}{}
		}
		if m.ClientKey.AppInstKey.ClusterInstKey.Developer != o.ClientKey.AppInstKey.ClusterInstKey.Developer {
			fields[AppInstClientFieldClientKeyAppInstKeyClusterInstKeyDeveloper] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKeyClusterInstKey] = struct{}{}
			fields[AppInstClientFieldClientKeyAppInstKey] = struct{}{}
			fields[AppInstClientFieldClientKey] = struct{}{}
		}
	} else if (m.ClientKey.AppInstKey != nil && o.ClientKey.AppInstKey == nil) || (m.ClientKey.AppInstKey == nil && o.ClientKey.AppInstKey != nil) {
		fields[AppInstClientFieldClientKeyAppInstKey] = struct{}{}
		fields[AppInstClientFieldClientKey] = struct{}{}
	}
	if m.ClientKey.Uuid != o.ClientKey.Uuid {
		fields[AppInstClientFieldClientKeyUuid] = struct{}{}
		fields[AppInstClientFieldClientKey] = struct{}{}
	}
	if m.Location.Latitude != o.Location.Latitude {
		fields[AppInstClientFieldLocationLatitude] = struct{}{}
		fields[AppInstClientFieldLocation] = struct{}{}
	}
	if m.Location.Longitude != o.Location.Longitude {
		fields[AppInstClientFieldLocationLongitude] = struct{}{}
		fields[AppInstClientFieldLocation] = struct{}{}
	}
	if m.Location.HorizontalAccuracy != o.Location.HorizontalAccuracy {
		fields[AppInstClientFieldLocationHorizontalAccuracy] = struct{}{}
		fields[AppInstClientFieldLocation] = struct{}{}
	}
	if m.Location.VerticalAccuracy != o.Location.VerticalAccuracy {
		fields[AppInstClientFieldLocationVerticalAccuracy] = struct{}{}
		fields[AppInstClientFieldLocation] = struct{}{}
	}
	if m.Location.Altitude != o.Location.Altitude {
		fields[AppInstClientFieldLocationAltitude] = struct{}{}
		fields[AppInstClientFieldLocation] = struct{}{}
	}
	if m.Location.Course != o.Location.Course {
		fields[AppInstClientFieldLocationCourse] = struct{}{}
		fields[AppInstClientFieldLocation] = struct{}{}
	}
	if m.Location.Speed != o.Location.Speed {
		fields[AppInstClientFieldLocationSpeed] = struct{}{}
		fields[AppInstClientFieldLocation] = struct{}{}
	}
	if m.Location.Timestamp != nil && o.Location.Timestamp != nil {
		if m.Location.Timestamp.Seconds != o.Location.Timestamp.Seconds {
			fields[AppInstClientFieldLocationTimestampSeconds] = struct{}{}
			fields[AppInstClientFieldLocationTimestamp] = struct{}{}
			fields[AppInstClientFieldLocation] = struct{}{}
		}
		if m.Location.Timestamp.Nanos != o.Location.Timestamp.Nanos {
			fields[AppInstClientFieldLocationTimestampNanos] = struct{}{}
			fields[AppInstClientFieldLocationTimestamp] = struct{}{}
			fields[AppInstClientFieldLocation] = struct{}{}
		}
	} else if (m.Location.Timestamp != nil && o.Location.Timestamp == nil) || (m.Location.Timestamp == nil && o.Location.Timestamp != nil) {
		fields[AppInstClientFieldLocationTimestamp] = struct{}{}
		fields[AppInstClientFieldLocation] = struct{}{}
	}
	if m.NotifyId != o.NotifyId {
		fields[AppInstClientFieldNotifyId] = struct{}{}
	}
	if m.Status != o.Status {
		fields[AppInstClientFieldStatus] = struct{}{}
	}
}

func (m *AppInstClient) CopyInFields(src *AppInstClient) int {
	changed := 0
	fmap := MakeFieldMap(src.Fields)
	if _, set := fmap["2"]; set {
		if _, set := fmap["2.1"]; set {
			if src.ClientKey.AppInstKey != nil {
				m.ClientKey.AppInstKey = &AppInstKey{}
				if _, set := fmap["2.1.1"]; set {
					if _, set := fmap["2.1.1.1"]; set {
						if _, set := fmap["2.1.1.1.2"]; set {
							if m.ClientKey.AppInstKey.AppKey.DeveloperKey.Name != src.ClientKey.AppInstKey.AppKey.DeveloperKey.Name {
								m.ClientKey.AppInstKey.AppKey.DeveloperKey.Name = src.ClientKey.AppInstKey.AppKey.DeveloperKey.Name
								changed++
							}
						}
					}
					if _, set := fmap["2.1.1.2"]; set {
						if m.ClientKey.AppInstKey.AppKey.Name != src.ClientKey.AppInstKey.AppKey.Name {
							m.ClientKey.AppInstKey.AppKey.Name = src.ClientKey.AppInstKey.AppKey.Name
							changed++
						}
					}
					if _, set := fmap["2.1.1.3"]; set {
						if m.ClientKey.AppInstKey.AppKey.Version != src.ClientKey.AppInstKey.AppKey.Version {
							m.ClientKey.AppInstKey.AppKey.Version = src.ClientKey.AppInstKey.AppKey.Version
							changed++
						}
					}
				}
				if _, set := fmap["2.1.4"]; set {
					if _, set := fmap["2.1.4.1"]; set {
						if _, set := fmap["2.1.4.1.1"]; set {
							if m.ClientKey.AppInstKey.ClusterInstKey.ClusterKey.Name != src.ClientKey.AppInstKey.ClusterInstKey.ClusterKey.Name {
								m.ClientKey.AppInstKey.ClusterInstKey.ClusterKey.Name = src.ClientKey.AppInstKey.ClusterInstKey.ClusterKey.Name
								changed++
							}
						}
					}
					if _, set := fmap["2.1.4.2"]; set {
						if _, set := fmap["2.1.4.2.1"]; set {
							if _, set := fmap["2.1.4.2.1.1"]; set {
								if m.ClientKey.AppInstKey.ClusterInstKey.CloudletKey.OperatorKey.Name != src.ClientKey.AppInstKey.ClusterInstKey.CloudletKey.OperatorKey.Name {
									m.ClientKey.AppInstKey.ClusterInstKey.CloudletKey.OperatorKey.Name = src.ClientKey.AppInstKey.ClusterInstKey.CloudletKey.OperatorKey.Name
									changed++
								}
							}
						}
						if _, set := fmap["2.1.4.2.2"]; set {
							if m.ClientKey.AppInstKey.ClusterInstKey.CloudletKey.Name != src.ClientKey.AppInstKey.ClusterInstKey.CloudletKey.Name {
								m.ClientKey.AppInstKey.ClusterInstKey.CloudletKey.Name = src.ClientKey.AppInstKey.ClusterInstKey.CloudletKey.Name
								changed++
							}
						}
					}
					if _, set := fmap["2.1.4.3"]; set {
						if m.ClientKey.AppInstKey.ClusterInstKey.Developer != src.ClientKey.AppInstKey.ClusterInstKey.Developer {
							m.ClientKey.AppInstKey.ClusterInstKey.Developer = src.ClientKey.AppInstKey.ClusterInstKey.Developer
							changed++
						}
					}
				}
			} else if m.ClientKey.AppInstKey != nil {
				m.ClientKey.AppInstKey = nil
				changed++
			}
		}
		if _, set := fmap["2.2"]; set {
			if m.ClientKey.Uuid != src.ClientKey.Uuid {
				m.ClientKey.Uuid = src.ClientKey.Uuid
				changed++
			}
		}
	}
	if _, set := fmap["3"]; set {
		if _, set := fmap["3.1"]; set {
			if m.Location.Latitude != src.Location.Latitude {
				m.Location.Latitude = src.Location.Latitude
				changed++
			}
		}
		if _, set := fmap["3.2"]; set {
			if m.Location.Longitude != src.Location.Longitude {
				m.Location.Longitude = src.Location.Longitude
				changed++
			}
		}
		if _, set := fmap["3.3"]; set {
			if m.Location.HorizontalAccuracy != src.Location.HorizontalAccuracy {
				m.Location.HorizontalAccuracy = src.Location.HorizontalAccuracy
				changed++
			}
		}
		if _, set := fmap["3.4"]; set {
			if m.Location.VerticalAccuracy != src.Location.VerticalAccuracy {
				m.Location.VerticalAccuracy = src.Location.VerticalAccuracy
				changed++
			}
		}
		if _, set := fmap["3.5"]; set {
			if m.Location.Altitude != src.Location.Altitude {
				m.Location.Altitude = src.Location.Altitude
				changed++
			}
		}
		if _, set := fmap["3.6"]; set {
			if m.Location.Course != src.Location.Course {
				m.Location.Course = src.Location.Course
				changed++
			}
		}
		if _, set := fmap["3.7"]; set {
			if m.Location.Speed != src.Location.Speed {
				m.Location.Speed = src.Location.Speed
				changed++
			}
		}
		if _, set := fmap["3.8"]; set {
			if src.Location.Timestamp != nil {
				m.Location.Timestamp = &distributed_match_engine.Timestamp{}
				if _, set := fmap["3.8.1"]; set {
					if m.Location.Timestamp.Seconds != src.Location.Timestamp.Seconds {
						m.Location.Timestamp.Seconds = src.Location.Timestamp.Seconds
						changed++
					}
				}
				if _, set := fmap["3.8.2"]; set {
					if m.Location.Timestamp.Nanos != src.Location.Timestamp.Nanos {
						m.Location.Timestamp.Nanos = src.Location.Timestamp.Nanos
						changed++
					}
				}
			} else if m.Location.Timestamp != nil {
				m.Location.Timestamp = nil
				changed++
			}
		}
	}
	if _, set := fmap["5"]; set {
		if m.NotifyId != src.NotifyId {
			m.NotifyId = src.NotifyId
			changed++
		}
	}
	if _, set := fmap["6"]; set {
		if m.Status != src.Status {
			m.Status = src.Status
			changed++
		}
	}
	return changed
}

// Helper method to check that enums have valid values
// NOTE: ValidateEnums checks all Fields even if some are not set
func (m *AppInstClient) ValidateEnums() error {
	if err := m.ClientKey.ValidateEnums(); err != nil {
		return err
	}
	if _, ok := AppInstClient_FindStatus_name[int32(m.Status)]; !ok {
		return errors.New("invalid Status")
	}
	return nil
}

func IgnoreAppInstClientFields(taglist string) cmp.Option {
	names := []string{}
	tags := make(map[string]struct{})
	for _, tag := range strings.Split(taglist, ",") {
		tags[tag] = struct{}{}
	}
	if _, found := tags["nocmp"]; found {
		names = append(names, "NotifyId")
	}
	return cmpopts.IgnoreFields(AppInstClient{}, names...)
}

var FindStatusStrings = []string{
	"FIND_UNKNOWN",
	"FIND_FOUND",
	"FIND_NOTFOUND",
}

const (
	FindStatusFIND_UNKNOWN  uint64 = 1 << 0
	FindStatusFIND_FOUND    uint64 = 1 << 1
	FindStatusFIND_NOTFOUND uint64 = 1 << 2
)

var AppInstClient_FindStatus_CamelName = map[int32]string{
	// FIND_UNKNOWN -> FindUnknown
	0: "FindUnknown",
	// FIND_FOUND -> FindFound
	1: "FindFound",
	// FIND_NOTFOUND -> FindNotfound
	2: "FindNotfound",
}
var AppInstClient_FindStatus_CamelValue = map[string]int32{
	"FindUnknown":  0,
	"FindFound":    1,
	"FindNotfound": 2,
}

func (e *AppInstClient_FindStatus) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var str string
	err := unmarshal(&str)
	if err != nil {
		return err
	}
	val, ok := AppInstClient_FindStatus_CamelValue[util.CamelCase(str)]
	if !ok {
		// may be enum value instead of string
		ival, err := strconv.Atoi(str)
		val = int32(ival)
		if err == nil {
			_, ok = AppInstClient_FindStatus_CamelName[val]
		}
	}
	if !ok {
		return errors.New(fmt.Sprintf("No enum value for %s", str))
	}
	*e = AppInstClient_FindStatus(val)
	return nil
}

func (e AppInstClient_FindStatus) MarshalYAML() (interface{}, error) {
	return proto.EnumName(AppInstClient_FindStatus_CamelName, int32(e)), nil
}

// custom JSON encoding/decoding
func (e *AppInstClient_FindStatus) UnmarshalJSON(b []byte) error {
	var str string
	err := json.Unmarshal(b, &str)
	if err == nil {
		val, ok := AppInstClient_FindStatus_CamelValue[util.CamelCase(str)]
		if !ok {
			// may be int value instead of enum name
			ival, err := strconv.Atoi(str)
			val = int32(ival)
			if err == nil {
				_, ok = AppInstClient_FindStatus_CamelName[val]
			}
		}
		if !ok {
			return errors.New(fmt.Sprintf("No enum value for %s", str))
		}
		*e = AppInstClient_FindStatus(val)
		return nil
	}
	var val int32
	err = json.Unmarshal(b, &val)
	if err == nil {
		*e = AppInstClient_FindStatus(val)
		return nil
	}
	return fmt.Errorf("No enum value for %v", b)
}
func (m *AppInstClientKey) Size() (n int) {
	var l int
	_ = l
	if m.AppInstKey != nil {
		l = m.AppInstKey.Size()
		n += 1 + l + sovClient(uint64(l))
	}
	l = len(m.Uuid)
	if l > 0 {
		n += 1 + l + sovClient(uint64(l))
	}
	return n
}

func (m *AppInstClient) Size() (n int) {
	var l int
	_ = l
	if len(m.Fields) > 0 {
		for _, s := range m.Fields {
			l = len(s)
			n += 1 + l + sovClient(uint64(l))
		}
	}
	l = m.ClientKey.Size()
	n += 1 + l + sovClient(uint64(l))
	l = m.Location.Size()
	n += 1 + l + sovClient(uint64(l))
	if m.NotifyId != 0 {
		n += 1 + sovClient(uint64(m.NotifyId))
	}
	if m.Status != 0 {
		n += 1 + sovClient(uint64(m.Status))
	}
	return n
}

func sovClient(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozClient(x uint64) (n int) {
	return sovClient(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AppInstClientKey) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClient
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AppInstClientKey: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AppInstClientKey: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AppInstKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClient
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.AppInstKey == nil {
				m.AppInstKey = &AppInstKey{}
			}
			if err := m.AppInstKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Uuid", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClient
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Uuid = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClient(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClient
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *AppInstClient) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClient
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AppInstClient: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AppInstClient: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Fields", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClient
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Fields = append(m.Fields, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ClientKey", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClient
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ClientKey.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Location", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClient
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Location.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field NotifyId", wireType)
			}
			m.NotifyId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.NotifyId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Status", wireType)
			}
			m.Status = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClient
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Status |= (AppInstClient_FindStatus(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClient(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthClient
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClient(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClient
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClient
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClient
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthClient
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowClient
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipClient(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthClient = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClient   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("client.proto", fileDescriptorClient) }

var fileDescriptorClient = []byte{
	// 579 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x52, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xcd, 0xa6, 0x6d, 0x54, 0xef, 0x2f, 0xed, 0x2f, 0x5d, 0xfe, 0x68, 0x09, 0x10, 0xa2, 0x70,
	0x89, 0xaa, 0xc6, 0x46, 0xe5, 0x00, 0x2a, 0x07, 0x48, 0x5b, 0x55, 0xaa, 0x8a, 0x1c, 0xc9, 0xa5,
	0x70, 0xb4, 0x1c, 0xef, 0xd6, 0x59, 0x61, 0xef, 0xae, 0xe2, 0x35, 0x25, 0x57, 0x3e, 0x02, 0x7c,
	0x89, 0x9e, 0xf9, 0x04, 0x3d, 0xe6, 0x88, 0x84, 0xb8, 0xa2, 0x12, 0x71, 0xe2, 0xc4, 0x21, 0xdc,
	0x91, 0xd7, 0x8e, 0x21, 0xa0, 0x88, 0x8b, 0xfd, 0x76, 0x66, 0xde, 0xcc, 0xd3, 0x9b, 0x81, 0x55,
	0x3f, 0x64, 0x94, 0x2b, 0x53, 0x0e, 0x85, 0x12, 0xc8, 0xa0, 0x24, 0xa0, 0x1a, 0xd6, 0x6f, 0x05,
	0x42, 0x04, 0x21, 0xb5, 0x3c, 0xc9, 0x2c, 0x8f, 0x73, 0xa1, 0x3c, 0xc5, 0x04, 0x8f, 0xb3, 0xc2,
	0x7a, 0x75, 0x48, 0xe3, 0x24, 0xcc, 0x69, 0xf5, 0x87, 0x01, 0x53, 0x83, 0xa4, 0x6f, 0xfa, 0x22,
	0xb2, 0x22, 0xd1, 0x67, 0x61, 0xda, 0xe6, 0xb5, 0x95, 0x7e, 0x3b, 0x7e, 0x28, 0x12, 0x62, 0xe9,
	0xba, 0x80, 0xf2, 0x02, 0xe4, 0xcc, 0xbd, 0x7f, 0x32, 0x49, 0x27, 0xf2, 0x94, 0x3f, 0xe8, 0x50,
	0x1e, 0x30, 0x4e, 0x2d, 0x12, 0xd1, 0x8e, 0xa6, 0x5a, 0xa1, 0xf0, 0xf3, 0x26, 0x86, 0x27, 0x65,
	0x0e, 0xd7, 0x3d, 0x29, 0x5d, 0xc6, 0xe3, 0x99, 0xb2, 0xff, 0x09, 0x7d, 0x45, 0x43, 0x21, 0xe9,
	0x30, 0x0f, 0x5c, 0x0d, 0x44, 0x20, 0xb2, 0x06, 0x29, 0xca, 0xa2, 0x2d, 0x17, 0xd6, 0xba, 0x52,
	0x1e, 0xf2, 0x58, 0xed, 0x69, 0x3b, 0x8e, 0xe8, 0x08, 0x3d, 0x80, 0xd5, 0x59, 0x33, 0xf7, 0x25,
	0x1d, 0x61, 0xd0, 0x04, 0xed, 0xff, 0xb6, 0xaf, 0x99, 0x85, 0x45, 0x66, 0x4e, 0x39, 0xa2, 0x23,
	0x07, 0x7a, 0x05, 0x46, 0x08, 0x2e, 0x27, 0x09, 0x23, 0xb8, 0xdc, 0x04, 0x6d, 0xc3, 0xd1, 0xb8,
	0x75, 0x59, 0x86, 0x6b, 0x73, 0x13, 0xd0, 0x75, 0x58, 0x39, 0x65, 0x34, 0x24, 0x31, 0x06, 0xcd,
	0xa5, 0xb6, 0xe1, 0xe4, 0x2f, 0xf4, 0x04, 0xc2, 0x6c, 0x25, 0x7a, 0x68, 0x59, 0x0f, 0xbd, 0xf9,
	0xf7, 0xd0, 0x42, 0xe7, 0xee, 0xf2, 0xf8, 0xf3, 0x9d, 0x92, 0x63, 0xf8, 0x85, 0xf0, 0xc7, 0x70,
	0x35, 0x14, 0xbe, 0x5e, 0x17, 0x5e, 0xd2, 0xfc, 0xdb, 0x26, 0x61, 0xb1, 0x1a, 0xb2, 0x7e, 0xa2,
	0x28, 0x71, 0xb5, 0x9f, 0x6e, 0xe6, 0xa7, 0xf9, 0x54, 0xf8, 0x79, 0x87, 0x82, 0x84, 0x36, 0xa1,
	0xc1, 0x85, 0x62, 0xa7, 0x23, 0x97, 0x11, 0xbc, 0xd2, 0x04, 0xed, 0xa5, 0xdd, 0xb5, 0xf3, 0x29,
	0x06, 0x6f, 0xdf, 0xdf, 0x58, 0xe1, 0xc2, 0x8f, 0xa4, 0xb3, 0x9a, 0xe5, 0x0f, 0x09, 0x7a, 0x04,
	0x2b, 0xb1, 0xf2, 0x54, 0x12, 0xe3, 0x4a, 0x13, 0xb4, 0xd7, 0xb7, 0xef, 0x2e, 0x92, 0x6a, 0x1e,
	0x30, 0x4e, 0x8e, 0x75, 0xa9, 0x93, 0x53, 0x5a, 0x5d, 0x08, 0x7f, 0x45, 0x51, 0x0d, 0x56, 0x0f,
	0x0e, 0xed, 0x7d, 0xf7, 0xc4, 0x3e, 0xb2, 0x7b, 0x2f, 0xec, 0x5a, 0x09, 0xad, 0x43, 0xa8, 0x23,
	0x07, 0xbd, 0x13, 0x7b, 0xbf, 0x06, 0xd0, 0x06, 0x5c, 0xd3, 0x6f, 0xbb, 0xf7, 0x2c, 0x0b, 0x95,
	0x77, 0x56, 0x2f, 0xa6, 0x18, 0x7c, 0x9f, 0xe2, 0xd2, 0xf6, 0x27, 0xf0, 0xc7, 0x12, 0xbb, 0x92,
	0xa1, 0x0b, 0x00, 0x37, 0x8e, 0x07, 0xe2, 0x6c, 0xde, 0x7b, 0xbc, 0x48, 0x64, 0x7d, 0x61, 0xa6,
	0x95, 0x7c, 0x9b, 0xe2, 0x9e, 0x43, 0x63, 0x91, 0x0c, 0x7d, 0x3a, 0x97, 0x8a, 0xb7, 0xba, 0x7e,
	0xea, 0xdb, 0x73, 0x46, 0xcf, 0xb6, 0x8a, 0xbd, 0xfc, 0x76, 0x1d, 0x29, 0x4c, 0x7f, 0xfb, 0xb3,
	0x5b, 0x4c, 0x1f, 0xb6, 0x17, 0xd1, 0xf3, 0x1f, 0x18, 0xbc, 0xf9, 0xf8, 0xf5, 0x5d, 0x19, 0xb7,
	0xae, 0x58, 0xf1, 0x40, 0x9c, 0x59, 0x9e, 0x94, 0xe9, 0xc1, 0x65, 0xcb, 0xdc, 0x01, 0x9b, 0xf7,
	0xc0, 0x6e, 0x6d, 0xfc, 0xa5, 0x51, 0x1a, 0x4f, 0x1a, 0xe0, 0xc3, 0xa4, 0x01, 0x2e, 0x27, 0x0d,
	0xd0, 0xaf, 0x68, 0x7d, 0xf7, 0x7f, 0x06, 0x00, 0x00, 0xff, 0xff, 0xda, 0xd1, 0x79, 0x2c, 0xbc,
	0x03, 0x00, 0x00,
}
