skipmethods:
  ShowAppInstInfo:
  ShowAppInstMetrics:
  ShowCloudletInfo:
  InjectCloudletInfo:
  EvictCloudletInfo:
  ShowCloudletMetrics:
  ShowClusterInstInfo:
  ShowController:
  ShowNode:
  ShowNodeLocal:
  RunCommand:
  SendLocalRequest:
  StreamNotice:
  ShowCloudletRefs:
  ShowClusterRefs:
skipfields:
  App:
    annotations:
    deployment_generator:
    permits_platform_apps:
    del_opt:
  AppInst:
    cloudlet_loc:
    liveness:
    mapped_ports:
    errors:
    crm_override:
    runtime_info:
    auto_cluster_ip_access:
    state:
  Cloudlet:
    time_limits:
  ClusterInst:
    liveness:
    auto:
    state:
    errors:
    crm_override:
    node_flavor:
