// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: developer.proto

package gencmd

import edgeproto "github.com/mobiledgex/edge-cloud/edgeproto"
import "strings"
import "time"
import "github.com/spf13/cobra"
import "context"
import "os"
import "io"
import "text/tabwriter"
import "github.com/spf13/pflag"
import "encoding/json"
import "github.com/mobiledgex/edge-cloud/protoc-gen-cmd/cmdsup"
import "github.com/mobiledgex/edge-cloud/protoc-gen-cmd/yaml"
import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/googleapis/google/api"
import _ "github.com/mobiledgex/edge-cloud/protogen"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// Auto-generated code: DO NOT EDIT
var DeveloperApiCmd edgeproto.DeveloperApiClient
var DeveloperIn edgeproto.Developer
var DeveloperFlagSet = pflag.NewFlagSet("Developer", pflag.ExitOnError)

func DeveloperKeySlicer(in *edgeproto.DeveloperKey) []string {
	s := make([]string, 0, 1)
	s = append(s, in.Name)
	return s
}

func DeveloperKeyHeaderSlicer() []string {
	s := make([]string, 0, 1)
	s = append(s, "Name")
	return s
}

func DeveloperSlicer(in *edgeproto.Developer) []string {
	s := make([]string, 0, 6)
	if in.Fields == nil {
		in.Fields = make([]string, 1)
	}
	s = append(s, in.Fields[0])
	s = append(s, in.Key.Name)
	s = append(s, in.Username)
	s = append(s, in.Passhash)
	s = append(s, in.Address)
	s = append(s, in.Email)
	return s
}

func DeveloperHeaderSlicer() []string {
	s := make([]string, 0, 6)
	s = append(s, "Fields")
	s = append(s, "Key-Name")
	s = append(s, "Username")
	s = append(s, "Passhash")
	s = append(s, "Address")
	s = append(s, "Email")
	return s
}

var CreateDeveloperCmd = &cobra.Command{
	Use: "CreateDeveloper",
	Run: func(cmd *cobra.Command, args []string) {
		if DeveloperApiCmd == nil {
			fmt.Println("DeveloperApi client not initialized")
			return
		}
		var err error
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		objs, err := DeveloperApiCmd.CreateDeveloper(ctx, &DeveloperIn)
		cancel()
		if err != nil {
			fmt.Println("CreateDeveloper failed: ", err)
			return
		}
		switch cmdsup.OutputFormat {
		case cmdsup.OutputFormatYaml:
			output, err := yaml.Marshal(objs)
			if err != nil {
				fmt.Printf("Yaml failed to marshal: %s\n", err)
				return
			}
			fmt.Print(string(output))
		case cmdsup.OutputFormatJson:
			output, err := json.MarshalIndent(objs, "", "  ")
			if err != nil {
				fmt.Printf("Json failed to marshal: %s\n", err)
				return
			}
			fmt.Println(string(output))
		case cmdsup.OutputFormatJsonCompact:
			output, err := json.Marshal(objs)
			if err != nil {
				fmt.Printf("Json failed to marshal: %s\n", err)
				return
			}
			fmt.Println(string(output))
		case cmdsup.OutputFormatTable:
			output := tabwriter.NewWriter(os.Stdout, 0, 0, 1, ' ', 0)
			fmt.Fprintln(output, strings.Join(ResultHeaderSlicer(), "\t"))
			fmt.Fprintln(output, strings.Join(ResultSlicer(objs), "\t"))
			output.Flush()
		}
	},
}

var DeleteDeveloperCmd = &cobra.Command{
	Use: "DeleteDeveloper",
	Run: func(cmd *cobra.Command, args []string) {
		if DeveloperApiCmd == nil {
			fmt.Println("DeveloperApi client not initialized")
			return
		}
		var err error
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		objs, err := DeveloperApiCmd.DeleteDeveloper(ctx, &DeveloperIn)
		cancel()
		if err != nil {
			fmt.Println("DeleteDeveloper failed: ", err)
			return
		}
		switch cmdsup.OutputFormat {
		case cmdsup.OutputFormatYaml:
			output, err := yaml.Marshal(objs)
			if err != nil {
				fmt.Printf("Yaml failed to marshal: %s\n", err)
				return
			}
			fmt.Print(string(output))
		case cmdsup.OutputFormatJson:
			output, err := json.MarshalIndent(objs, "", "  ")
			if err != nil {
				fmt.Printf("Json failed to marshal: %s\n", err)
				return
			}
			fmt.Println(string(output))
		case cmdsup.OutputFormatJsonCompact:
			output, err := json.Marshal(objs)
			if err != nil {
				fmt.Printf("Json failed to marshal: %s\n", err)
				return
			}
			fmt.Println(string(output))
		case cmdsup.OutputFormatTable:
			output := tabwriter.NewWriter(os.Stdout, 0, 0, 1, ' ', 0)
			fmt.Fprintln(output, strings.Join(ResultHeaderSlicer(), "\t"))
			fmt.Fprintln(output, strings.Join(ResultSlicer(objs), "\t"))
			output.Flush()
		}
	},
}

var UpdateDeveloperCmd = &cobra.Command{
	Use: "UpdateDeveloper",
	Run: func(cmd *cobra.Command, args []string) {
		if DeveloperApiCmd == nil {
			fmt.Println("DeveloperApi client not initialized")
			return
		}
		var err error
		DeveloperSetFields()
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		objs, err := DeveloperApiCmd.UpdateDeveloper(ctx, &DeveloperIn)
		cancel()
		if err != nil {
			fmt.Println("UpdateDeveloper failed: ", err)
			return
		}
		switch cmdsup.OutputFormat {
		case cmdsup.OutputFormatYaml:
			output, err := yaml.Marshal(objs)
			if err != nil {
				fmt.Printf("Yaml failed to marshal: %s\n", err)
				return
			}
			fmt.Print(string(output))
		case cmdsup.OutputFormatJson:
			output, err := json.MarshalIndent(objs, "", "  ")
			if err != nil {
				fmt.Printf("Json failed to marshal: %s\n", err)
				return
			}
			fmt.Println(string(output))
		case cmdsup.OutputFormatJsonCompact:
			output, err := json.Marshal(objs)
			if err != nil {
				fmt.Printf("Json failed to marshal: %s\n", err)
				return
			}
			fmt.Println(string(output))
		case cmdsup.OutputFormatTable:
			output := tabwriter.NewWriter(os.Stdout, 0, 0, 1, ' ', 0)
			fmt.Fprintln(output, strings.Join(ResultHeaderSlicer(), "\t"))
			fmt.Fprintln(output, strings.Join(ResultSlicer(objs), "\t"))
			output.Flush()
		}
	},
}

var ShowDeveloperCmd = &cobra.Command{
	Use: "ShowDeveloper",
	Run: func(cmd *cobra.Command, args []string) {
		if DeveloperApiCmd == nil {
			fmt.Println("DeveloperApi client not initialized")
			return
		}
		var err error
		ctx, cancel := context.WithTimeout(context.Background(), 3*time.Second)
		defer cancel()
		stream, err := DeveloperApiCmd.ShowDeveloper(ctx, &DeveloperIn)
		if err != nil {
			fmt.Println("ShowDeveloper failed: ", err)
			return
		}
		objs := make([]*edgeproto.Developer, 0)
		for {
			obj, err := stream.Recv()
			if err == io.EOF {
				break
			}
			if err != nil {
				fmt.Println("ShowDeveloper recv failed: ", err)
				break
			}
			objs = append(objs, obj)
		}
		if len(objs) == 0 {
			return
		}
		switch cmdsup.OutputFormat {
		case cmdsup.OutputFormatYaml:
			output, err := yaml.Marshal(objs)
			if err != nil {
				fmt.Printf("Yaml failed to marshal: %s\n", err)
				return
			}
			fmt.Print(string(output))
		case cmdsup.OutputFormatJson:
			output, err := json.MarshalIndent(objs, "", "  ")
			if err != nil {
				fmt.Printf("Json failed to marshal: %s\n", err)
				return
			}
			fmt.Println(string(output))
		case cmdsup.OutputFormatJsonCompact:
			output, err := json.Marshal(objs)
			if err != nil {
				fmt.Printf("Json failed to marshal: %s\n", err)
				return
			}
			fmt.Println(string(output))
		case cmdsup.OutputFormatTable:
			output := tabwriter.NewWriter(os.Stdout, 0, 0, 1, ' ', 0)
			fmt.Fprintln(output, strings.Join(DeveloperHeaderSlicer(), "\t"))
			for _, obj := range objs {
				fmt.Fprintln(output, strings.Join(DeveloperSlicer(obj), "\t"))
			}
			output.Flush()
		}
	},
}

func init() {
	DeveloperFlagSet.StringVar(&DeveloperIn.Key.Name, "key-name", "", "Key.Name")
	DeveloperFlagSet.StringVar(&DeveloperIn.Username, "username", "", "Username")
	DeveloperFlagSet.StringVar(&DeveloperIn.Passhash, "passhash", "", "Passhash")
	DeveloperFlagSet.StringVar(&DeveloperIn.Address, "address", "", "Address")
	DeveloperFlagSet.StringVar(&DeveloperIn.Email, "email", "", "Email")
	CreateDeveloperCmd.Flags().AddFlagSet(DeveloperFlagSet)
	DeleteDeveloperCmd.Flags().AddFlagSet(DeveloperFlagSet)
	UpdateDeveloperCmd.Flags().AddFlagSet(DeveloperFlagSet)
	ShowDeveloperCmd.Flags().AddFlagSet(DeveloperFlagSet)
}

func DeveloperSetFields() {
	DeveloperIn.Fields = make([]string, 0)
	if DeveloperFlagSet.Lookup("key-name").Changed {
		DeveloperIn.Fields = append(DeveloperIn.Fields, "2.2")
	}
	if DeveloperFlagSet.Lookup("username").Changed {
		DeveloperIn.Fields = append(DeveloperIn.Fields, "3")
	}
	if DeveloperFlagSet.Lookup("passhash").Changed {
		DeveloperIn.Fields = append(DeveloperIn.Fields, "4")
	}
	if DeveloperFlagSet.Lookup("address").Changed {
		DeveloperIn.Fields = append(DeveloperIn.Fields, "5")
	}
	if DeveloperFlagSet.Lookup("email").Changed {
		DeveloperIn.Fields = append(DeveloperIn.Fields, "6")
	}
}
