- name: start cloudlet
  gather_facts: yes
  user: ubuntu
  become: yes
  hosts: mexservers
  vars_files:
    - mex_vars.yml
 
  tasks:

  - name: show CRM startup variables
    debug:
       var: crm

  - name: start up crmserver process
    shell: "nohup {{ crm_remote_bin }} --apiAddr 0.0.0.0:37001 --notifyAddrs {{ crm.ctrladdr }} --cloudletKey '{{ crm.cloudletkey }}' --tls {{ remote_tls_path }}/mex-server.crt  --d api,notify,mexos > {{ remote_log_path }}/{{ crm.name }}.log 2>&1 &"
    environment:
      CLOUDLET_KIND: dind
      NETWORK_SCHEME: publicip
      MEXENV_URL: https://vault.mobiledgex.net/v1/secret/data/cloudlet/openstack/mexenv.json

