- name: stop matching processes
  gather_facts: no
  user: ubuntu
  become: yes
  hosts: mexservers

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:
  - name: "kill processes for {{ processbin }} matching {{ processargs }}"
    shell: "true||pkill -9 -f \"{{ processbin }} .*{{ processargs}}\""


