- name: startup etcds
  gather_facts: yes
  user: root
  hosts: etcds

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:

  - name: start up etcd process
    shell: "nohup etcd  --name {{ item.etcdlocal.name }} --data-dir {{ item.etcdlocal.datadir }} --listen-peer-urls {{ item.etcdlocal.peeraddrs }} --listen-client-urls {{ item.etcdlocal.clientaddrs }} --advertise-client-urls {{ item.etcdlocal.clientaddrs }} --initial-advertise-peer-urls  {{ item.etcdlocal.peeraddrs }} --initial-cluster {{ item.etcdlocal.initialcluster }} -log-output stdout >> {{ remote_log_path }}/{{ item.etcdlocal.name }}.log 2>&1 &"
    when: item.hostname == inventory_hostname 
    with_items:
       -  "{{ etcds }}"

- name: startup controllers
  gather_facts: yes
  user: root
  hosts: controllers

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:
  - name: start up controller process
    shell: "nohup controller --etcdUrls {{ item.controllerlocal.etcdaddrs }} --apiAddr {{ item.controllerlocal.apiaddr }} --notifyAddr {{ item.controllerlocal.notifyaddr }} --httpAddr {{ item.controllerlocal.httpaddr }} > {{ remote_log_path }}/{{ item.controllerlocal.name }}.log 2>&1 &"
    when: item.hostname == inventory_hostname
    with_items:
       -  "{{ controllers }}"

- name: startup dmes
  gather_facts: yes
  user: root
  hosts: dmes

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:
  - name: start up dme-server process
    shell: "nohup dme-server --apiAddr {{ item.dmelocal.apiaddr }} --notifyAddrs {{ item.dmelocal.notifyaddrs }} > {{ remote_log_path }}/{{ item.dmelocal.name }}.log 2>&1 &"
    when: item.hostname == inventory_hostname 
    with_items:
       -  "{{ dmes }}"


- name: startup crms
  gather_facts: yes
  user: root
  hosts: crms

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks: 
  - name: start up crmserver process
    shell: "nohup crmserver --apiAddr {{ item.crmlocal.apiaddr }} --notifyAddrs {{ item.crmlocal.notifyaddrs }} > {{ remote_log_path }}/{{ item.crmlocal.name }}.log 2>&1 &"
    when: item.hostname == inventory_hostname
    with_items:
       -  "{{ crms }}"

