- name: reset and stop etcds
  gather_facts: no
  user: root
  hosts: etcds

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:
  - name: stop etcd process
    shell: "pkill -9 etcd||true"
    when: item.hostname == inventory_hostname 
    with_items:
       -  "{{ etcds }}"

  - name: reset etcd data
    file:
      state: absent
      path: "{{ item.etcdlocal.datadir }}"
    when: item.hostname == inventory_hostname 
    with_items:
       -  "{{ etcds }}"

- name: stop controllers
  gather_facts: no
  user: root
  hosts: controllers

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:

  - name: stop controller process
    shell: "pkill -9 controller|| true"
    when: item.hostname == inventory_hostname 
    with_items:
       -  "{{ controllers }}"


- name: stop dmes
  gather_facts: no
  user: root
  hosts: dmes

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:

  - name: stop dme-server process
    shell: "pkill -9 dme-server||true"
    when: item.hostname == inventory_hostname 
    with_items:
       -  "{{ dmes }}"
       
- name: stop crms
  gather_facts: no
  user: root
  hosts: crms

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:
  - name: stop crmserver process
    shell: "pkill -9 crmserver||true"
    when: item.hostname == inventory_hostname 
    with_items:
       -  "{{ crms }}"


- name: stop locsims
  gather_facts: no
  user: root
  hosts: locsims

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:
  - name: stop locsim process
    shell: "pkill -9 loc-api-sim||true"
    when: item.hostname == inventory_hostname
    with_items:
       -  "{{ locsims }}"
