- name: startup etcds
  gather_facts: no
  user: root
  hosts: etcds

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:

  - name: start up etcd process
    shell: "nohup etcd  --name {{ item.etcdlocal.name }} --data-dir {{ item.etcdlocal.datadir }} --listen-peer-urls {{ item.etcdlocal.peeraddrs }} --listen-client-urls {{ item.etcdlocal.clientaddrs }} --advertise-client-urls {{ item.etcdlocal.clientaddrs }} --initial-advertise-peer-urls  {{ item.etcdlocal.peeraddrs }} --initial-cluster {{ item.etcdlocal.initialcluster }} -log-output stdout >> {{ remote_log_path }}/{{ item.etcdlocal.name }}.log 2>&1 &"
    when: item.hostname == inventory_hostname 
    with_items:
       -  "{{ etcds }}"

- name: startup controllers
  gather_facts: no
  user: root
  hosts: controllers

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:

  - name: set the docker creds
    set_fact: mex_docker_reg_pass="{{ lookup('env','MEX_DOCKER_REG_PASS') }}"

  - name: docker login to mex repo
    docker_login:
      registry: registry.mobiledgex.net:5000
      username: mobiledgex
      password: "{{mex_docker_reg_pass}}"

 
  - name: set tls option
    set_fact:
       tlsopt: "{% if controllers[0].controllerlocal.tls.servercert == '' %}  {% else %} --tls {{remote_tls_path}}/{{controllers[0].controllerlocal.tls.servercert|basename}} {% endif %}"
 

  - name: start up controller container
    docker_container:
       pull: yes
       image: "{{ item.dockerimage }}"
       name: "{{ item.controllerlocal.name }}"
       command: "controller --etcdUrls {{ item.controllerlocal.etcdaddrs }} --apiAddr {{ item.controllerlocal.apiaddr }} --notifyAddr {{ item.controllerlocal.notifyaddr }} --httpAddr {{ item.controllerlocal.httpaddr }} {{ tlsopt }}  -d etcd,api,notify"
       network_mode: host
       restart_policy: unless-stopped
    when: item.hostname == inventory_hostname and item.dockerimage != ""
    with_items:
       -  "{{ controllers }}"

- name: startup dmes
  gather_facts: no
  user: root
  hosts: dmes

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:
  - name: set the docker creds
    set_fact: mex_docker_reg_pass="{{ lookup('env','MEX_DOCKER_REG_PASS') }}"

  - name: docker login to mex repo
    docker_login:
      registry: registry.mobiledgex.net:5000
      username: mobiledgex
      password: "{{mex_docker_reg_pass}}"

  - name: set tls option
    set_fact:
       tlsopt: "{% if dmes[0].dmelocal.tls.servercert == '' %}  {% else %} --tls {{remote_tls_path}}/{{dmes[0].dmelocal.tls.servercert|basename}} {% endif %}"

  - name: create remote log dir
    file:
       state: directory
       path: "{{ remote_log_path }}"

  - name: make dme env file
    copy: content="{{ item.envvars|to_nice_yaml|regex_replace(':\\s', '=') }}" dest="{{remote_log_path}}/{{item.dmelocal.name}}.env"
    when: item.dockerimage != "" and item.envvars|length >0
    with_items:
      - "{{dmes}}"

  - name: start up dme-server container
    docker_container:
       pull: yes
       image: "{{ item.dockerimage }}"
       name: "{{ item.dmelocal.name }}"
       env_file: "{{remote_log_path}}//{{item.dmelocal.name}}.env"
       command: "dme-server --apiAddr {{ item.dmelocal.apiaddr }} --httpAddr {{ item.dmelocal.httpaddr }} --notifyAddrs {{ item.dmelocal.notifyaddrs }} --locverurl \"{{ item.dmelocal.locverurl }}\" --toksrvurl \"{{ item.dmelocal.toksrvurl }}\" --carrier {{ item.dmelocal.carrier }} --vaultAddr {{ item.dmelocal.vaultaddr }} --cloudletKey '{{ item.dmelocal.cloudletkey }}' {{ tlsopt }} -d locapi,dmedb,dmereq"
       network_mode: host
       restart_policy: unless-stopped
    when: item.hostname == inventory_hostname and item.dockerimage != ""
    with_items:
       -  "{{ dmes }}"

  - name: set creds from variables
    set_fact:
        envvar:  "{% if dmes[0].envvars['LOCAPI_USER'] is defined %} export LOCAPI_USER={{ dmes[0].envvars['LOCAPI_USER'] }} LOCAPI_PASSWD={{ dmes[0].envvars['LOCAPI_PASSWD']}}  {% else %} true {% endif %}" 


- name: startup crms
  gather_facts: no
  user: root
  hosts: crms

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:
 
  - name: set the docker creds
    set_fact: mex_docker_reg_pass="{{ lookup('env','MEX_DOCKER_REG_PASS') }}"

  - name: docker login to mex repo
    docker_login:
      registry: registry.mobiledgex.net:5000
      username: mobiledgex
      password: "{{mex_docker_reg_pass}}"

  - name: set tls option
    set_fact:
       tlsopt: "{% if crms[0].crmlocal.tls.servercert == '' %}  {% else %} --tls {{remote_tls_path}}/{{crms[0].crmlocal.tls.servercert|basename}} {% endif %}"

  - name: create remote log dir
    file:
       state: directory
       path: "{{ remote_log_path }}"


  - name: start up crmserver container
    docker_container:
      pull: yes
      image: "{{ item.dockerimage }}"
      name: "{{ item.crmlocal.name }}"
      command: "crmserver --apiAddr {{ item.crmlocal.apiaddr }} --notifyAddrs {{ item.crmlocal.notifyaddrs }} --cloudletKey '{{ item.crmlocal.cloudletkey }}' {{ tlsopt }} --fakecloudlet={{ item.crmlocal.fakecloudlet }} --d api,notify,mexos"
      network_mode: host
      restart_policy: unless-stopped
    when: item.hostname == inventory_hostname and item.dockerimage != ""
    with_items:
       -  "{{ crms }}"


- name: startup location api simulators
  gather_facts: no
  user: root
  hosts: locsims

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:

  - name: start up locsim container
    docker_container:
       pull: yes
       image: "{{ item.dockerimage }}"
       name: "{{ item.locapisimlocal.name }}"
       command: "loc-api-sim --port {{ item.locapisimlocal.port }} --file {{ locsim_remote_data_file }}  --geo {{ locsim_remote_data_dir }}/geocode.dat --country {{ item.locapisimlocal.country }}"
       network_mode: host
       volumes:
         - /var/tmp:/var/tmp
       restart_policy: unless-stopped
    when: item.hostname == inventory_hostname and item.dockerimage != ""
    with_items:
       -  "{{ locsims }}"

- name: startup token server simulators
  gather_facts: no
  user: root
  hosts: toksims

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:

  - name: start up toksim container
    docker_container:
       pull: yes
       image: "{{ item.dockerimage }}"
       name: "{{ item.toksrvsimlocal.name }}"
       command: "tok-srv-sim --port {{ item.toksrvsimlocal.port }} "
       network_mode: host
       restart_policy: unless-stopped
    when: item.hostname == inventory_hostname and item.dockerimage != ""
    with_items:
       -  "{{ toksims }}"

- name: startup sample apps
  gather_facts: no
  user: root
  hosts: sampleapps

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:
  - name: set the docker creds
    set_fact: mex_docker_reg_pass="{{ lookup('env','MEX_DOCKER_REG_PASS') }}"

  - name: docker login to developer repo
    docker_login:
      registry: "{{ item.dockerimage }}"
      username: mobiledgex
      password: "{{mex_docker_reg_pass}}"
    when: item.hostname == inventory_hostname and item.dockerimage != ""
    with_items: 
      - "{{ sampleapps }}"

  - name: start up application container with command
    docker_container:
       pull: yes
       image: "{{ item.dockerimage }}"
       name: "{{ item.sampleapplocal.name }}"
       entrypoint: "{{ item.command }}" 
       network_mode: host
       restart_policy: unless-stopped
       volumes: "{{ item.volumemounts }}"
    when: item.hostname == inventory_hostname and item.dockerimage != "" and item.command != ""
    with_items:
       -  "{{ sampleapps }}"

  - name: start up application container no command
    docker_container:
       pull: yes
       image: "{{ item.dockerimage }}"
       name: "{{ item.sampleapplocal.name }}"
       network_mode: host
       restart_policy: unless-stopped
       volumes: "{{ item.volumemounts }}"
    when: item.hostname == inventory_hostname and item.dockerimage != "" and item.command == ""
    with_items:
       -  "{{ sampleapps }}"


- name: startup vault
  gather_facts: no
  user: root
  hosts: vaults

  vars_files:
  - mex_vars.yml
  - "{{ setupfile }}"

  tasks:
  - name: set the docker creds
    set_fact: mex_docker_reg_pass="{{ lookup('env','MEX_DOCKER_REG_PASS') }}"

  - name: docker login to developer repo
    docker_login:
      registry: "{{ item.dockerimage }}"
      username: mobiledgex
      password: "{{mex_docker_reg_pass}}"
    when: item.hostname == inventory_hostname and item.dockerimage != ""
    with_items:
      - "{{ vaults }}"

  - name: make vault env file
    copy: content="{{ item.envvars|to_nice_yaml|regex_replace(':\\s', '=') }}" dest="{{remote_log_path}}/{{item.vault.name}}.env"
    when: item.dockerimage != "" and item.envvars|length >0
    with_items:
      - "{{vaults}}"

  - name: start up vault container 
    docker_container:
       pull: yes
       image: "{{ item.dockerimage }}"
       name: "{{ item.vault.name }}"
       network_mode: host
       restart_policy: unless-stopped
       privileged: yes
       env_file: "{{remote_log_path}}//{{item.vault.name}}.env"
    when: item.hostname == inventory_hostname and item.dockerimage != ""
    with_items:
       -  "{{ vaults }}"

    
