  
  - gopath: "{{ lookup('env', 'GOPATH') }}"
  - tlsoutdir: "{{ gopath }}/src/github.com/mobiledgex/edge-cloud/tls/out"
  - server_to_path:
      Linux_x86_64: "{{ gopath }}/bin/linux_amd64"
      Darwin_x86_64: "{{ gopath }}/bin"
 
  - servertype: "{{ ansible_system }}_{{ ansible_architecture }}"
  - local_binpath: "{{ server_to_path[servertype] }}"
  - controller_bin: "{{ local_binpath }}/controller"
  - crm_bin: "{{ local_binpath }}/crmserver" 
  - dme_bin: "{{ local_binpath }}/dme-server"
  - locsim_bin: "{{ local_binpath }}/loc-api-sim"
  - toksim_bin: "{{ local_binpath }}/tok-srv-sim"
  - remote_bin_path: /usr/local/bin
  - controller_remote_bin: "{{ remote_bin_path }}/controller"
  - crm_remote_bin: "{{ remote_bin_path }}/crmserver"  
  - dme_remote_bin: "{{ remote_bin_path }}/dme-server"
  - locsim_remote_bin: "{{ remote_bin_path }}/loc-api-sim"
  - locsim_data_file: locsim.yml
  - locsim_remote_data_dir: /var/tmp
  - locsim_remote_data_file: "{{ locsim_remote_data_dir }}/{{ locsim_data_file }}"
  - toksim_remote_bin: "{{ remote_bin_path }}/tok-srv-sim"
  - remote_log_path: /var/log/mex
  - setupfile: setup.yml
  - etcd_url: https://github.com/coreos/etcd/releases/download
  - etcd_version: v3.3.8
 
