  
  - gopath: "{{ lookup('env', 'GOPATH') }}"
  - tlsoutdir: "{{ gopath }}/src/github.com/mobiledgex/edge-cloud/tls/out"
  - server_to_path:
      Linux_x86_64: "{{ gopath }}/bin/linux_amd64"
      Linux_aarch64: "{{ gopath }}/bin/linux_arm64"
      Darwin_x86_64: "{{ gopath }}/bin"
  - mex_docker_reg_pass: sandhill
  - vault_token: 0eb94cce-ab3f-33a3-bd66-0046e8743a14
  - kubeadm_dind_image_tag: 596f7d093470c1dc3a3e4466bcdfb34438a99b90-v1.13
  - mexosagent_local_svc: "{{ gopath }}/src/github.com/mobiledgex/edge-cloud-infra/openstack-tenant/agent/mexosagent.service" 
  - mexosagent_remote_svc: "/etc/systemd/system/mexosagent.service"
  - crmserver_remote_svc:  "/etc/systemd/system/crmserver.service"
  - vault_token: "0eb94cce-ab3f-33a3-bd66-0046e8743a14"
  - servertype: "{{ ansible_system }}_{{ ansible_architecture }}"
  - local_binpath: "{{ server_to_path[servertype] }}"
  - local_plugin_file: "{{ gopath }}/plugins/linux_amd64/platforms.so"
  - remote_plugin_path: "/plugins/"
  - remote_plugin_file: "/plugins/platforms.so"
  - controller_bin: "{{ local_binpath }}/controller"
  - crm_bin: "{{ local_binpath }}/crmserver" 
  - dme_bin: "{{ local_binpath }}/dme-server"
  - locsim_bin: "{{ local_binpath }}/loc-api-sim"
  - toksim_bin: "{{ local_binpath }}/tok-srv-sim"
  - mexosagent_local_bin: "{{ local_binpath }}/agent"
  - mexosagent_remote_bin: "/usr/local/bin/mexosagent"
  - remote_bin_path: /usr/local/bin
  - controller_remote_bin: "{{ remote_bin_path }}/controller"
  - crm_remote_bin: "{{ remote_bin_path }}/crmserver"  
  - dme_remote_bin: "{{ remote_bin_path }}/dme-server"
  - locsim_remote_bin: "{{ remote_bin_path }}/loc-api-sim"
  - locsim_data_file: locsim.yml
  - locsim_remote_data_dir: /var/tmp
  - locsim_remote_data_file: "{{ locsim_remote_data_dir }}/{{ locsim_data_file }}"
  - toksim_remote_bin: "{{ remote_bin_path }}/tok-srv-sim"
  - remote_log_path: /var/log/mex
  - remote_tls_path: /root/tls
  - mex_path: /root/.mobiledgex
  - setupfile: setup.yml
  - etcd_url: https://github.com/coreos/etcd/releases/download
  - etcd_version: v3.3.8
 
