// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: appcommon.proto

package distributed_match_engine

import (
	"encoding/json"
	"errors"
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	"github.com/mobiledgex/edge-cloud/util"
	io "io"
	math "math"
	math_bits "math/bits"
	"strconv"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// Layer4 Protocol
//
// LProto indicates which protocol to use for accessing an application on a particular port. This is required by Kubernetes for port mapping.
//
// 0: `L_PROTO_UNKNOWN`
// 1: `L_PROTO_TCP`
// 2: `L_PROTO_UDP`
type LProto int32

const (
	// Unknown protocol
	LProto_L_PROTO_UNKNOWN LProto = 0
	// TCP (L4) protocol
	LProto_L_PROTO_TCP LProto = 1
	// UDP (L4) protocol
	LProto_L_PROTO_UDP LProto = 2
)

var LProto_name = map[int32]string{
	0: "L_PROTO_UNKNOWN",
	1: "L_PROTO_TCP",
	2: "L_PROTO_UDP",
}

var LProto_value = map[string]int32{
	"L_PROTO_UNKNOWN": 0,
	"L_PROTO_TCP":     1,
	"L_PROTO_UDP":     2,
}

func (x LProto) String() string {
	return proto.EnumName(LProto_name, int32(x))
}

func (LProto) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fdc58d2114e550de, []int{0}
}

// Health check status
//
// Health check status gets set by external, or rootLB health check
type HealthCheck int32

const (
	// Health Check is unknown
	HealthCheck_HEALTH_CHECK_UNKNOWN HealthCheck = 0
	// Health Check failure due to RootLB being offline
	HealthCheck_HEALTH_CHECK_FAIL_ROOTLB_OFFLINE HealthCheck = 1
	// Health Check failure due to Backend server being unavailable
	HealthCheck_HEALTH_CHECK_FAIL_SERVER_FAIL HealthCheck = 2
	// Health Check is ok
	HealthCheck_HEALTH_CHECK_OK HealthCheck = 3
)

var HealthCheck_name = map[int32]string{
	0: "HEALTH_CHECK_UNKNOWN",
	1: "HEALTH_CHECK_FAIL_ROOTLB_OFFLINE",
	2: "HEALTH_CHECK_FAIL_SERVER_FAIL",
	3: "HEALTH_CHECK_OK",
}

var HealthCheck_value = map[string]int32{
	"HEALTH_CHECK_UNKNOWN":             0,
	"HEALTH_CHECK_FAIL_ROOTLB_OFFLINE": 1,
	"HEALTH_CHECK_FAIL_SERVER_FAIL":    2,
	"HEALTH_CHECK_OK":                  3,
}

func (x HealthCheck) String() string {
	return proto.EnumName(HealthCheck_name, int32(x))
}

func (HealthCheck) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fdc58d2114e550de, []int{1}
}

// CloudletState is the state of the Cloudlet.
type CloudletState int32

const (
	// Unknown
	CloudletState_CLOUDLET_STATE_UNKNOWN CloudletState = 0
	// Create/Delete/Update encountered errors (see Errors field of CloudletInfo)
	CloudletState_CLOUDLET_STATE_ERRORS CloudletState = 1
	// Cloudlet is created and ready
	CloudletState_CLOUDLET_STATE_READY CloudletState = 2
	// Cloudlet is offline (unreachable)
	CloudletState_CLOUDLET_STATE_OFFLINE CloudletState = 3
	// Cloudlet is not present
	CloudletState_CLOUDLET_STATE_NOT_PRESENT CloudletState = 4
	// Cloudlet is initializing
	CloudletState_CLOUDLET_STATE_INIT CloudletState = 5
	// Cloudlet is upgrading
	CloudletState_CLOUDLET_STATE_UPGRADE CloudletState = 6
	// Cloudlet needs data to synchronize
	CloudletState_CLOUDLET_STATE_NEED_SYNC CloudletState = 7
)

var CloudletState_name = map[int32]string{
	0: "CLOUDLET_STATE_UNKNOWN",
	1: "CLOUDLET_STATE_ERRORS",
	2: "CLOUDLET_STATE_READY",
	3: "CLOUDLET_STATE_OFFLINE",
	4: "CLOUDLET_STATE_NOT_PRESENT",
	5: "CLOUDLET_STATE_INIT",
	6: "CLOUDLET_STATE_UPGRADE",
	7: "CLOUDLET_STATE_NEED_SYNC",
}

var CloudletState_value = map[string]int32{
	"CLOUDLET_STATE_UNKNOWN":     0,
	"CLOUDLET_STATE_ERRORS":      1,
	"CLOUDLET_STATE_READY":       2,
	"CLOUDLET_STATE_OFFLINE":     3,
	"CLOUDLET_STATE_NOT_PRESENT": 4,
	"CLOUDLET_STATE_INIT":        5,
	"CLOUDLET_STATE_UPGRADE":     6,
	"CLOUDLET_STATE_NEED_SYNC":   7,
}

func (x CloudletState) String() string {
	return proto.EnumName(CloudletState_name, int32(x))
}

func (CloudletState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fdc58d2114e550de, []int{2}
}

// Cloudlet Maintenance States
//
// Maintenance allows for planned downtimes of Cloudlets.
// These states involve message exchanges between the Controller,
// the AutoProv service, and the CRM. Certain states are only set
// by certain actors.
type MaintenanceState int32

const (
	// Normal operational state
	MaintenanceState_NORMAL_OPERATION MaintenanceState = 0
	// Request start of maintenance
	MaintenanceState_MAINTENANCE_START MaintenanceState = 1
	// Trigger failover for any HA AppInsts
	MaintenanceState_FAILOVER_REQUESTED MaintenanceState = 2
	// Failover done
	MaintenanceState_FAILOVER_DONE MaintenanceState = 3
	// Some errors encountered during maintenance failover
	MaintenanceState_FAILOVER_ERROR MaintenanceState = 4
	// Request start of maintenance without AutoProv failover
	MaintenanceState_MAINTENANCE_START_NO_FAILOVER MaintenanceState = 5
	// Request CRM to transition to maintenance
	MaintenanceState_CRM_REQUESTED MaintenanceState = 6
	// CRM request done and under maintenance
	MaintenanceState_CRM_UNDER_MAINTENANCE MaintenanceState = 7
	// CRM failed to go into maintenance
	MaintenanceState_CRM_ERROR MaintenanceState = 8
	// Request CRM to transition to normal operation
	MaintenanceState_NORMAL_OPERATION_INIT MaintenanceState = 9
	// Under maintenance
	MaintenanceState_UNDER_MAINTENANCE MaintenanceState = 31
)

var MaintenanceState_name = map[int32]string{
	0:  "NORMAL_OPERATION",
	1:  "MAINTENANCE_START",
	2:  "FAILOVER_REQUESTED",
	3:  "FAILOVER_DONE",
	4:  "FAILOVER_ERROR",
	5:  "MAINTENANCE_START_NO_FAILOVER",
	6:  "CRM_REQUESTED",
	7:  "CRM_UNDER_MAINTENANCE",
	8:  "CRM_ERROR",
	9:  "NORMAL_OPERATION_INIT",
	31: "UNDER_MAINTENANCE",
}

var MaintenanceState_value = map[string]int32{
	"NORMAL_OPERATION":              0,
	"MAINTENANCE_START":             1,
	"FAILOVER_REQUESTED":            2,
	"FAILOVER_DONE":                 3,
	"FAILOVER_ERROR":                4,
	"MAINTENANCE_START_NO_FAILOVER": 5,
	"CRM_REQUESTED":                 6,
	"CRM_UNDER_MAINTENANCE":         7,
	"CRM_ERROR":                     8,
	"NORMAL_OPERATION_INIT":         9,
	"UNDER_MAINTENANCE":             31,
}

func (x MaintenanceState) String() string {
	return proto.EnumName(MaintenanceState_name, int32(x))
}

func (MaintenanceState) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_fdc58d2114e550de, []int{3}
}

// Application Port
//
// AppPort describes an L4 or L7 public access port/path mapping. This is used to track external to internal mappings for access via a shared load balancer or reverse proxy.
type AppPort struct {
	// TCP (L4) or UDP (L4) protocol
	Proto LProto `protobuf:"varint,1,opt,name=proto,proto3,enum=distributed_match_engine.LProto" json:"proto,omitempty"`
	// Container port
	InternalPort int32 `protobuf:"varint,2,opt,name=internal_port,json=internalPort,proto3" json:"internal_port,omitempty"`
	// Public facing port for TCP/UDP (may be mapped on shared LB reverse proxy)
	PublicPort int32 `protobuf:"varint,3,opt,name=public_port,json=publicPort,proto3" json:"public_port,omitempty"`
	// skip 4 to preserve the numbering. 4 was path_prefix but was removed since we dont need it after removed http
	// FQDN prefix to append to base FQDN in FindCloudlet response. May be empty.
	FqdnPrefix string `protobuf:"bytes,5,opt,name=fqdn_prefix,json=fqdnPrefix,proto3" json:"fqdn_prefix,omitempty"`
	// A non-zero end port indicates a port range from internal port to end port, inclusive.
	EndPort int32 `protobuf:"varint,6,opt,name=end_port,json=endPort,proto3" json:"end_port,omitempty"`
	// TLS termination for this port
	Tls bool `protobuf:"varint,7,opt,name=tls,proto3" json:"tls,omitempty"`
	// use nginx proxy for this port if you really need a transparent proxy (udp only)
	Nginx                bool     `protobuf:"varint,8,opt,name=nginx,proto3" json:"nginx,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AppPort) Reset()         { *m = AppPort{} }
func (m *AppPort) String() string { return proto.CompactTextString(m) }
func (*AppPort) ProtoMessage()    {}
func (*AppPort) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdc58d2114e550de, []int{0}
}
func (m *AppPort) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *AppPort) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_AppPort.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *AppPort) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AppPort.Merge(m, src)
}
func (m *AppPort) XXX_Size() int {
	return m.Size()
}
func (m *AppPort) XXX_DiscardUnknown() {
	xxx_messageInfo_AppPort.DiscardUnknown(m)
}

var xxx_messageInfo_AppPort proto.InternalMessageInfo

//
// DeviceInfoStatic
type DeviceInfoStatic struct {
	// Android or iOS
	DeviceOs string `protobuf:"bytes,1,opt,name=device_os,json=deviceOs,proto3" json:"device_os,omitempty"`
	// Device model
	DeviceModel          string   `protobuf:"bytes,2,opt,name=device_model,json=deviceModel,proto3" json:"device_model,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceInfoStatic) Reset()         { *m = DeviceInfoStatic{} }
func (m *DeviceInfoStatic) String() string { return proto.CompactTextString(m) }
func (*DeviceInfoStatic) ProtoMessage()    {}
func (*DeviceInfoStatic) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdc58d2114e550de, []int{1}
}
func (m *DeviceInfoStatic) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeviceInfoStatic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeviceInfoStatic.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeviceInfoStatic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfoStatic.Merge(m, src)
}
func (m *DeviceInfoStatic) XXX_Size() int {
	return m.Size()
}
func (m *DeviceInfoStatic) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfoStatic.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfoStatic proto.InternalMessageInfo

//
// DeviceInfoDynamic
type DeviceInfoDynamic struct {
	// LTE, 5G, etc.
	DataNetworkType string `protobuf:"bytes,1,opt,name=data_network_type,json=dataNetworkType,proto3" json:"data_network_type,omitempty"`
	// Device signal strength
	SignalStrength uint64 `protobuf:"varint,2,opt,name=signal_strength,json=signalStrength,proto3" json:"signal_strength,omitempty"`
	// Carrier name (can be different from cloudlet org if using "")
	CarrierName          string   `protobuf:"bytes,3,opt,name=carrier_name,json=carrierName,proto3" json:"carrier_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceInfoDynamic) Reset()         { *m = DeviceInfoDynamic{} }
func (m *DeviceInfoDynamic) String() string { return proto.CompactTextString(m) }
func (*DeviceInfoDynamic) ProtoMessage()    {}
func (*DeviceInfoDynamic) Descriptor() ([]byte, []int) {
	return fileDescriptor_fdc58d2114e550de, []int{2}
}
func (m *DeviceInfoDynamic) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *DeviceInfoDynamic) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_DeviceInfoDynamic.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *DeviceInfoDynamic) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceInfoDynamic.Merge(m, src)
}
func (m *DeviceInfoDynamic) XXX_Size() int {
	return m.Size()
}
func (m *DeviceInfoDynamic) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceInfoDynamic.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceInfoDynamic proto.InternalMessageInfo

var E_EnumBackend = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.EnumValueOptions)(nil),
	ExtensionType: (*bool)(nil),
	Field:         51042,
	Name:          "distributed_match_engine.enum_backend",
	Tag:           "varint,51042,opt,name=enum_backend",
	Filename:      "appcommon.proto",
}

func init() {
	proto.RegisterEnum("distributed_match_engine.LProto", LProto_name, LProto_value)
	proto.RegisterEnum("distributed_match_engine.HealthCheck", HealthCheck_name, HealthCheck_value)
	proto.RegisterEnum("distributed_match_engine.CloudletState", CloudletState_name, CloudletState_value)
	proto.RegisterEnum("distributed_match_engine.MaintenanceState", MaintenanceState_name, MaintenanceState_value)
	proto.RegisterType((*AppPort)(nil), "distributed_match_engine.AppPort")
	proto.RegisterType((*DeviceInfoStatic)(nil), "distributed_match_engine.DeviceInfoStatic")
	proto.RegisterType((*DeviceInfoDynamic)(nil), "distributed_match_engine.DeviceInfoDynamic")
	proto.RegisterExtension(E_EnumBackend)
}

func init() { proto.RegisterFile("appcommon.proto", fileDescriptor_fdc58d2114e550de) }

var fileDescriptor_fdc58d2114e550de = []byte{
	// 825 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x94, 0x4f, 0x6f, 0xe3, 0x44,
	0x18, 0xc6, 0xd7, 0x49, 0xf3, 0xef, 0x4d, 0xdb, 0x4c, 0xa7, 0x2d, 0xeb, 0xed, 0xee, 0xa6, 0x69,
	0x41, 0xa2, 0xca, 0x21, 0x2b, 0x81, 0xc4, 0x81, 0x0b, 0x72, 0xe3, 0x29, 0x8d, 0x9a, 0x78, 0xc2,
	0xc4, 0x59, 0xb4, 0xa7, 0x91, 0x63, 0x4f, 0x53, 0xab, 0xc9, 0xd8, 0x38, 0x13, 0xd8, 0x7e, 0x00,
	0x4e, 0x48, 0x88, 0x8f, 0xc4, 0x71, 0x8f, 0x7c, 0x04, 0xe8, 0x95, 0x03, 0x37, 0xce, 0x68, 0x6c,
	0x67, 0x37, 0x9b, 0x96, 0x9b, 0xf3, 0x7b, 0x9e, 0xf7, 0x99, 0xf7, 0x7d, 0x47, 0x19, 0x68, 0x78,
	0x71, 0xec, 0x47, 0xf3, 0x79, 0x24, 0x3b, 0x71, 0x12, 0xa9, 0x08, 0x9b, 0x41, 0xb8, 0x50, 0x49,
	0x38, 0x59, 0x2a, 0x11, 0xf0, 0xb9, 0xa7, 0xfc, 0x1b, 0x2e, 0xe4, 0x34, 0x94, 0xe2, 0xa8, 0x35,
	0x8d, 0xa2, 0xe9, 0x4c, 0xbc, 0x4a, 0x7d, 0x93, 0xe5, 0xf5, 0xab, 0x40, 0x2c, 0xfc, 0x24, 0x8c,
	0x55, 0x94, 0x64, 0xb5, 0xa7, 0x7f, 0x1b, 0x50, 0xb1, 0xe2, 0x78, 0x18, 0x25, 0x0a, 0x7f, 0x05,
	0xa5, 0x14, 0x9a, 0x46, 0xcb, 0x38, 0xdb, 0xfd, 0xa2, 0xd5, 0xf9, 0xbf, 0xdc, 0x4e, 0x7f, 0xa8,
	0x7d, 0x2c, 0xb3, 0xe3, 0x4f, 0x61, 0x27, 0x94, 0x4a, 0x24, 0xd2, 0x9b, 0xf1, 0x38, 0x4a, 0x94,
	0x59, 0x68, 0x19, 0x67, 0x25, 0xb6, 0xbd, 0x82, 0x69, 0xf8, 0x31, 0xd4, 0xe3, 0xe5, 0x64, 0x16,
	0xfa, 0x99, 0xa5, 0x98, 0x5a, 0x20, 0x43, 0x2b, 0xc3, 0xf5, 0x0f, 0x81, 0xe4, 0x71, 0x22, 0xae,
	0xc3, 0xb7, 0x66, 0xa9, 0x65, 0x9c, 0xd5, 0x18, 0x68, 0x34, 0x4c, 0x09, 0x7e, 0x06, 0x55, 0x21,
	0x83, 0xac, 0xbc, 0x9c, 0x96, 0x57, 0x84, 0x0c, 0xd2, 0x5a, 0x04, 0x45, 0x35, 0x5b, 0x98, 0x95,
	0x96, 0x71, 0x56, 0x65, 0xfa, 0x13, 0x1f, 0x40, 0x49, 0xb7, 0xfa, 0xd6, 0xac, 0xa6, 0x2c, 0xfb,
	0x71, 0xca, 0x00, 0xd9, 0xe2, 0xc7, 0xd0, 0x17, 0x3d, 0x79, 0x1d, 0x8d, 0x94, 0xa7, 0x42, 0x1f,
	0x3f, 0x87, 0x5a, 0x90, 0x32, 0x1e, 0x2d, 0xd2, 0xc9, 0x6b, 0xac, 0x9a, 0x01, 0xba, 0xc0, 0x27,
	0xb0, 0x9d, 0x8b, 0xf3, 0x28, 0x10, 0xb3, 0x74, 0xb2, 0x1a, 0xab, 0x67, 0x6c, 0xa0, 0xd1, 0xe9,
	0x2f, 0x06, 0xec, 0x7d, 0x08, 0xb5, 0xef, 0xa4, 0x37, 0x0f, 0x7d, 0xdc, 0x86, 0xbd, 0xc0, 0x53,
	0x1e, 0x97, 0x42, 0xfd, 0x14, 0x25, 0xb7, 0x5c, 0xdd, 0xc5, 0x22, 0x4f, 0x6f, 0x68, 0xc1, 0xc9,
	0xb8, 0x7b, 0x17, 0x0b, 0xfc, 0x39, 0x34, 0x16, 0xe1, 0x54, 0x6f, 0x6f, 0xa1, 0x12, 0x21, 0xa7,
	0xea, 0x26, 0x3d, 0x67, 0x8b, 0xed, 0x66, 0x78, 0x94, 0x53, 0xdd, 0x8d, 0xef, 0x25, 0x49, 0x28,
	0x12, 0x2e, 0xbd, 0xb9, 0x48, 0x97, 0x58, 0x63, 0xf5, 0x9c, 0x39, 0xde, 0x5c, 0xb4, 0xbf, 0x81,
	0x72, 0x76, 0x39, 0x78, 0x1f, 0x1a, 0x7d, 0x3e, 0x64, 0xd4, 0xa5, 0x7c, 0xec, 0x5c, 0x39, 0xf4,
	0x7b, 0x07, 0x3d, 0xc1, 0x0d, 0xa8, 0xaf, 0xa0, 0xdb, 0x1d, 0x22, 0x63, 0x1d, 0x8c, 0xed, 0x21,
	0x2a, 0xb4, 0x7f, 0x36, 0xa0, 0x7e, 0x29, 0xbc, 0x99, 0xba, 0xe9, 0xde, 0x08, 0xff, 0x16, 0x9b,
	0x70, 0x70, 0x49, 0xac, 0xbe, 0x7b, 0xc9, 0xbb, 0x97, 0xa4, 0x7b, 0xb5, 0x96, 0xf5, 0x19, 0xb4,
	0x3e, 0x52, 0x2e, 0xac, 0x5e, 0x9f, 0x33, 0x4a, 0xdd, 0xfe, 0x39, 0xa7, 0x17, 0x17, 0xfd, 0x9e,
	0x43, 0x90, 0x81, 0x4f, 0xe0, 0xe5, 0x43, 0xd7, 0x88, 0xb0, 0xd7, 0x84, 0xa5, 0xdf, 0xa8, 0xa0,
	0x3b, 0xfd, 0xc8, 0x42, 0xaf, 0x50, 0xb1, 0xfd, 0x8f, 0x01, 0x3b, 0xdd, 0x59, 0xb4, 0x0c, 0x66,
	0x42, 0xe9, 0x9b, 0x12, 0xf8, 0x08, 0x3e, 0xe9, 0xf6, 0xe9, 0xd8, 0xee, 0x13, 0x97, 0x8f, 0x5c,
	0xcb, 0x25, 0x6b, 0xbd, 0x3c, 0x83, 0xc3, 0x0d, 0x8d, 0x30, 0x46, 0xd9, 0x08, 0x19, 0x7a, 0x80,
	0x0d, 0x89, 0x11, 0xcb, 0x7e, 0x83, 0x0a, 0x8f, 0x04, 0xae, 0xda, 0x2e, 0xe2, 0x26, 0x1c, 0x6d,
	0x68, 0x0e, 0x75, 0xf9, 0x90, 0x91, 0x11, 0x71, 0x5c, 0xb4, 0x85, 0x9f, 0xc2, 0xfe, 0x86, 0xde,
	0x73, 0x7a, 0x2e, 0x2a, 0x3d, 0xd6, 0xe5, 0xf0, 0x5b, 0x66, 0xd9, 0x04, 0x95, 0xf1, 0x0b, 0x30,
	0x37, 0x43, 0x09, 0xb1, 0xf9, 0xe8, 0x8d, 0xd3, 0x45, 0x95, 0xf6, 0xef, 0x05, 0x40, 0x03, 0x4f,
	0xff, 0x69, 0xa4, 0x27, 0x7d, 0x91, 0x0d, 0x7d, 0x00, 0xc8, 0xa1, 0x6c, 0x60, 0xf5, 0x39, 0x1d,
	0x12, 0x66, 0xb9, 0x3d, 0xaa, 0xc7, 0x3d, 0x84, 0xbd, 0x81, 0xd5, 0x73, 0x5c, 0xe2, 0x58, 0x4e,
	0x97, 0xe8, 0x2c, 0xe6, 0x22, 0x03, 0xbf, 0x00, 0xac, 0x57, 0x4a, 0xf5, 0x6e, 0x19, 0xf9, 0x6e,
	0x4c, 0x46, 0x2e, 0xb1, 0x51, 0xe1, 0x68, 0xeb, 0xb7, 0x7f, 0x4d, 0x03, 0x3f, 0x85, 0x9d, 0xf7,
	0xaa, 0x4d, 0xf5, 0x94, 0xb9, 0x60, 0xc2, 0xee, 0x7b, 0x21, 0x5d, 0x1b, 0xda, 0xca, 0x95, 0x13,
	0x78, 0xf9, 0xe0, 0x1c, 0xee, 0x50, 0xbe, 0xb2, 0xa3, 0x92, 0x4e, 0xed, 0xb2, 0xc1, 0xda, 0x71,
	0xe5, 0xbc, 0xf6, 0x18, 0x0e, 0xb5, 0x30, 0x76, 0x6c, 0xc2, 0xf8, 0x5a, 0x0a, 0xaa, 0xe4, 0x86,
	0x7d, 0xa8, 0x69, 0x43, 0x76, 0x62, 0xf5, 0x43, 0xd5, 0xe6, 0xbc, 0xd9, 0x66, 0x6b, 0xb9, 0xe1,
	0x39, 0xec, 0x3d, 0x8c, 0x3c, 0xce, 0xc4, 0xaf, 0x2f, 0x60, 0x5b, 0xc8, 0xe5, 0x9c, 0x4f, 0x3c,
	0xff, 0x56, 0xc8, 0x00, 0x9f, 0x74, 0xb2, 0x07, 0xb0, 0xb3, 0x7a, 0x00, 0x3b, 0x44, 0x2e, 0xe7,
	0xaf, 0xbd, 0xd9, 0x52, 0xd0, 0x58, 0x85, 0x91, 0x5c, 0x98, 0xf7, 0xbf, 0x16, 0xd3, 0x17, 0xa2,
	0xae, 0x0b, 0xcf, 0xb3, 0xba, 0x73, 0xf4, 0xee, 0xaf, 0xe6, 0x93, 0x77, 0xf7, 0x4d, 0xe3, 0x8f,
	0xfb, 0xa6, 0xf1, 0xe7, 0x7d, 0xd3, 0x98, 0x94, 0xd3, 0x84, 0x2f, 0xff, 0x0b, 0x00, 0x00, 0xff,
	0xff, 0xff, 0x59, 0x18, 0x3d, 0x7d, 0x05, 0x00, 0x00,
}

func (m *AppPort) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *AppPort) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *AppPort) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Nginx {
		i--
		if m.Nginx {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x40
	}
	if m.Tls {
		i--
		if m.Tls {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x38
	}
	if m.EndPort != 0 {
		i = encodeVarintAppcommon(dAtA, i, uint64(m.EndPort))
		i--
		dAtA[i] = 0x30
	}
	if len(m.FqdnPrefix) > 0 {
		i -= len(m.FqdnPrefix)
		copy(dAtA[i:], m.FqdnPrefix)
		i = encodeVarintAppcommon(dAtA, i, uint64(len(m.FqdnPrefix)))
		i--
		dAtA[i] = 0x2a
	}
	if m.PublicPort != 0 {
		i = encodeVarintAppcommon(dAtA, i, uint64(m.PublicPort))
		i--
		dAtA[i] = 0x18
	}
	if m.InternalPort != 0 {
		i = encodeVarintAppcommon(dAtA, i, uint64(m.InternalPort))
		i--
		dAtA[i] = 0x10
	}
	if m.Proto != 0 {
		i = encodeVarintAppcommon(dAtA, i, uint64(m.Proto))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *DeviceInfoStatic) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeviceInfoStatic) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeviceInfoStatic) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.DeviceModel) > 0 {
		i -= len(m.DeviceModel)
		copy(dAtA[i:], m.DeviceModel)
		i = encodeVarintAppcommon(dAtA, i, uint64(len(m.DeviceModel)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.DeviceOs) > 0 {
		i -= len(m.DeviceOs)
		copy(dAtA[i:], m.DeviceOs)
		i = encodeVarintAppcommon(dAtA, i, uint64(len(m.DeviceOs)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *DeviceInfoDynamic) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *DeviceInfoDynamic) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *DeviceInfoDynamic) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if len(m.CarrierName) > 0 {
		i -= len(m.CarrierName)
		copy(dAtA[i:], m.CarrierName)
		i = encodeVarintAppcommon(dAtA, i, uint64(len(m.CarrierName)))
		i--
		dAtA[i] = 0x1a
	}
	if m.SignalStrength != 0 {
		i = encodeVarintAppcommon(dAtA, i, uint64(m.SignalStrength))
		i--
		dAtA[i] = 0x10
	}
	if len(m.DataNetworkType) > 0 {
		i -= len(m.DataNetworkType)
		copy(dAtA[i:], m.DataNetworkType)
		i = encodeVarintAppcommon(dAtA, i, uint64(len(m.DataNetworkType)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintAppcommon(dAtA []byte, offset int, v uint64) int {
	offset -= sovAppcommon(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *AppPort) CopyInFields(src *AppPort) int {
	changed := 0
	if m.Proto != src.Proto {
		m.Proto = src.Proto
		changed++
	}
	if m.InternalPort != src.InternalPort {
		m.InternalPort = src.InternalPort
		changed++
	}
	if m.PublicPort != src.PublicPort {
		m.PublicPort = src.PublicPort
		changed++
	}
	if m.FqdnPrefix != src.FqdnPrefix {
		m.FqdnPrefix = src.FqdnPrefix
		changed++
	}
	if m.EndPort != src.EndPort {
		m.EndPort = src.EndPort
		changed++
	}
	if m.Tls != src.Tls {
		m.Tls = src.Tls
		changed++
	}
	if m.Nginx != src.Nginx {
		m.Nginx = src.Nginx
		changed++
	}
	return changed
}

func (m *AppPort) DeepCopyIn(src *AppPort) {
	m.Proto = src.Proto
	m.InternalPort = src.InternalPort
	m.PublicPort = src.PublicPort
	m.FqdnPrefix = src.FqdnPrefix
	m.EndPort = src.EndPort
	m.Tls = src.Tls
	m.Nginx = src.Nginx
}

// Helper method to check that enums have valid values
func (m *AppPort) ValidateEnums() error {
	if _, ok := LProto_name[int32(m.Proto)]; !ok {
		return errors.New("invalid Proto")
	}
	return nil
}

func (m *DeviceInfoStatic) CopyInFields(src *DeviceInfoStatic) int {
	changed := 0
	if m.DeviceOs != src.DeviceOs {
		m.DeviceOs = src.DeviceOs
		changed++
	}
	if m.DeviceModel != src.DeviceModel {
		m.DeviceModel = src.DeviceModel
		changed++
	}
	return changed
}

func (m *DeviceInfoStatic) DeepCopyIn(src *DeviceInfoStatic) {
	m.DeviceOs = src.DeviceOs
	m.DeviceModel = src.DeviceModel
}

// Helper method to check that enums have valid values
func (m *DeviceInfoStatic) ValidateEnums() error {
	return nil
}

func (m *DeviceInfoDynamic) CopyInFields(src *DeviceInfoDynamic) int {
	changed := 0
	if m.DataNetworkType != src.DataNetworkType {
		m.DataNetworkType = src.DataNetworkType
		changed++
	}
	if m.SignalStrength != src.SignalStrength {
		m.SignalStrength = src.SignalStrength
		changed++
	}
	if m.CarrierName != src.CarrierName {
		m.CarrierName = src.CarrierName
		changed++
	}
	return changed
}

func (m *DeviceInfoDynamic) DeepCopyIn(src *DeviceInfoDynamic) {
	m.DataNetworkType = src.DataNetworkType
	m.SignalStrength = src.SignalStrength
	m.CarrierName = src.CarrierName
}

// Helper method to check that enums have valid values
func (m *DeviceInfoDynamic) ValidateEnums() error {
	return nil
}

var LProtoStrings = []string{
	"L_PROTO_UNKNOWN",
	"L_PROTO_TCP",
	"L_PROTO_UDP",
}

const (
	LProtoL_PROTO_UNKNOWN uint64 = 1 << 0
	LProtoL_PROTO_TCP     uint64 = 1 << 1
	LProtoL_PROTO_UDP     uint64 = 1 << 2
)

var LProto_CamelName = map[int32]string{
	// L_PROTO_UNKNOWN -> LProtoUnknown
	0: "LProtoUnknown",
	// L_PROTO_TCP -> LProtoTcp
	1: "LProtoTcp",
	// L_PROTO_UDP -> LProtoUdp
	2: "LProtoUdp",
}
var LProto_CamelValue = map[string]int32{
	"LProtoUnknown": 0,
	"LProtoTcp":     1,
	"LProtoUdp":     2,
}

func (e *LProto) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var str string
	err := unmarshal(&str)
	if err != nil {
		return err
	}
	val, ok := LProto_CamelValue[util.CamelCase(str)]
	if !ok {
		// may have omitted common prefix
		val, ok = LProto_CamelValue["LProto"+util.CamelCase(str)]
	}
	if !ok {
		// may be enum value instead of string
		ival, err := strconv.Atoi(str)
		val = int32(ival)
		if err == nil {
			_, ok = LProto_CamelName[val]
		}
	}
	if !ok {
		return errors.New(fmt.Sprintf("No enum value for %s", str))
	}
	*e = LProto(val)
	return nil
}

func (e LProto) MarshalYAML() (interface{}, error) {
	str := proto.EnumName(LProto_CamelName, int32(e))
	str = strings.TrimPrefix(str, "LProto")
	return str, nil
}

// custom JSON encoding/decoding
func (e *LProto) UnmarshalJSON(b []byte) error {
	var str string
	err := json.Unmarshal(b, &str)
	if err == nil {
		val, ok := LProto_CamelValue[util.CamelCase(str)]
		if !ok {
			// may have omitted common prefix
			val, ok = LProto_CamelValue["LProto"+util.CamelCase(str)]
		}
		if !ok {
			// may be int value instead of enum name
			ival, err := strconv.Atoi(str)
			val = int32(ival)
			if err == nil {
				_, ok = LProto_CamelName[val]
			}
		}
		if !ok {
			return errors.New(fmt.Sprintf("No enum value for %s", str))
		}
		*e = LProto(val)
		return nil
	}
	var val int32
	err = json.Unmarshal(b, &val)
	if err == nil {
		*e = LProto(val)
		return nil
	}
	return fmt.Errorf("No enum value for %v", b)
}

/*
 * This is removed because we do not have enough time in
 * release 3.0 to update the SDK, UI, and documentation for this
 * change. It should be done in 3.1.
func (e LProto) MarshalJSON() ([]byte, error) {
	str := proto.EnumName(LProto_CamelName, int32(e))
	str = strings.TrimPrefix(str, "LProto")
	return json.Marshal(str)
}
*/
var LProtoCommonPrefix = "LProto"

var HealthCheckStrings = []string{
	"HEALTH_CHECK_UNKNOWN",
	"HEALTH_CHECK_FAIL_ROOTLB_OFFLINE",
	"HEALTH_CHECK_FAIL_SERVER_FAIL",
	"HEALTH_CHECK_OK",
}

const (
	HealthCheckHEALTH_CHECK_UNKNOWN             uint64 = 1 << 0
	HealthCheckHEALTH_CHECK_FAIL_ROOTLB_OFFLINE uint64 = 1 << 1
	HealthCheckHEALTH_CHECK_FAIL_SERVER_FAIL    uint64 = 1 << 2
	HealthCheckHEALTH_CHECK_OK                  uint64 = 1 << 3
)

var HealthCheck_CamelName = map[int32]string{
	// HEALTH_CHECK_UNKNOWN -> HealthCheckUnknown
	0: "HealthCheckUnknown",
	// HEALTH_CHECK_FAIL_ROOTLB_OFFLINE -> HealthCheckFailRootlbOffline
	1: "HealthCheckFailRootlbOffline",
	// HEALTH_CHECK_FAIL_SERVER_FAIL -> HealthCheckFailServerFail
	2: "HealthCheckFailServerFail",
	// HEALTH_CHECK_OK -> HealthCheckOk
	3: "HealthCheckOk",
}
var HealthCheck_CamelValue = map[string]int32{
	"HealthCheckUnknown":           0,
	"HealthCheckFailRootlbOffline": 1,
	"HealthCheckFailServerFail":    2,
	"HealthCheckOk":                3,
}

func (e *HealthCheck) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var str string
	err := unmarshal(&str)
	if err != nil {
		return err
	}
	val, ok := HealthCheck_CamelValue[util.CamelCase(str)]
	if !ok {
		// may have omitted common prefix
		val, ok = HealthCheck_CamelValue["HealthCheck"+util.CamelCase(str)]
	}
	if !ok {
		// may be enum value instead of string
		ival, err := strconv.Atoi(str)
		val = int32(ival)
		if err == nil {
			_, ok = HealthCheck_CamelName[val]
		}
	}
	if !ok {
		return errors.New(fmt.Sprintf("No enum value for %s", str))
	}
	*e = HealthCheck(val)
	return nil
}

func (e HealthCheck) MarshalYAML() (interface{}, error) {
	str := proto.EnumName(HealthCheck_CamelName, int32(e))
	str = strings.TrimPrefix(str, "HealthCheck")
	return str, nil
}

// custom JSON encoding/decoding
func (e *HealthCheck) UnmarshalJSON(b []byte) error {
	var str string
	err := json.Unmarshal(b, &str)
	if err == nil {
		val, ok := HealthCheck_CamelValue[util.CamelCase(str)]
		if !ok {
			// may have omitted common prefix
			val, ok = HealthCheck_CamelValue["HealthCheck"+util.CamelCase(str)]
		}
		if !ok {
			// may be int value instead of enum name
			ival, err := strconv.Atoi(str)
			val = int32(ival)
			if err == nil {
				_, ok = HealthCheck_CamelName[val]
			}
		}
		if !ok {
			return errors.New(fmt.Sprintf("No enum value for %s", str))
		}
		*e = HealthCheck(val)
		return nil
	}
	var val int32
	err = json.Unmarshal(b, &val)
	if err == nil {
		*e = HealthCheck(val)
		return nil
	}
	return fmt.Errorf("No enum value for %v", b)
}

/*
 * This is removed because we do not have enough time in
 * release 3.0 to update the SDK, UI, and documentation for this
 * change. It should be done in 3.1.
func (e HealthCheck) MarshalJSON() ([]byte, error) {
	str := proto.EnumName(HealthCheck_CamelName, int32(e))
	str = strings.TrimPrefix(str, "HealthCheck")
	return json.Marshal(str)
}
*/
var HealthCheckCommonPrefix = "HealthCheck"

var CloudletStateStrings = []string{
	"CLOUDLET_STATE_UNKNOWN",
	"CLOUDLET_STATE_ERRORS",
	"CLOUDLET_STATE_READY",
	"CLOUDLET_STATE_OFFLINE",
	"CLOUDLET_STATE_NOT_PRESENT",
	"CLOUDLET_STATE_INIT",
	"CLOUDLET_STATE_UPGRADE",
	"CLOUDLET_STATE_NEED_SYNC",
}

const (
	CloudletStateCLOUDLET_STATE_UNKNOWN     uint64 = 1 << 0
	CloudletStateCLOUDLET_STATE_ERRORS      uint64 = 1 << 1
	CloudletStateCLOUDLET_STATE_READY       uint64 = 1 << 2
	CloudletStateCLOUDLET_STATE_OFFLINE     uint64 = 1 << 3
	CloudletStateCLOUDLET_STATE_NOT_PRESENT uint64 = 1 << 4
	CloudletStateCLOUDLET_STATE_INIT        uint64 = 1 << 5
	CloudletStateCLOUDLET_STATE_UPGRADE     uint64 = 1 << 6
	CloudletStateCLOUDLET_STATE_NEED_SYNC   uint64 = 1 << 7
)

var CloudletState_CamelName = map[int32]string{
	// CLOUDLET_STATE_UNKNOWN -> CloudletStateUnknown
	0: "CloudletStateUnknown",
	// CLOUDLET_STATE_ERRORS -> CloudletStateErrors
	1: "CloudletStateErrors",
	// CLOUDLET_STATE_READY -> CloudletStateReady
	2: "CloudletStateReady",
	// CLOUDLET_STATE_OFFLINE -> CloudletStateOffline
	3: "CloudletStateOffline",
	// CLOUDLET_STATE_NOT_PRESENT -> CloudletStateNotPresent
	4: "CloudletStateNotPresent",
	// CLOUDLET_STATE_INIT -> CloudletStateInit
	5: "CloudletStateInit",
	// CLOUDLET_STATE_UPGRADE -> CloudletStateUpgrade
	6: "CloudletStateUpgrade",
	// CLOUDLET_STATE_NEED_SYNC -> CloudletStateNeedSync
	7: "CloudletStateNeedSync",
}
var CloudletState_CamelValue = map[string]int32{
	"CloudletStateUnknown":    0,
	"CloudletStateErrors":     1,
	"CloudletStateReady":      2,
	"CloudletStateOffline":    3,
	"CloudletStateNotPresent": 4,
	"CloudletStateInit":       5,
	"CloudletStateUpgrade":    6,
	"CloudletStateNeedSync":   7,
}

func (e *CloudletState) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var str string
	err := unmarshal(&str)
	if err != nil {
		return err
	}
	val, ok := CloudletState_CamelValue[util.CamelCase(str)]
	if !ok {
		// may have omitted common prefix
		val, ok = CloudletState_CamelValue["CloudletState"+util.CamelCase(str)]
	}
	if !ok {
		// may be enum value instead of string
		ival, err := strconv.Atoi(str)
		val = int32(ival)
		if err == nil {
			_, ok = CloudletState_CamelName[val]
		}
	}
	if !ok {
		return errors.New(fmt.Sprintf("No enum value for %s", str))
	}
	*e = CloudletState(val)
	return nil
}

func (e CloudletState) MarshalYAML() (interface{}, error) {
	str := proto.EnumName(CloudletState_CamelName, int32(e))
	str = strings.TrimPrefix(str, "CloudletState")
	return str, nil
}

// custom JSON encoding/decoding
func (e *CloudletState) UnmarshalJSON(b []byte) error {
	var str string
	err := json.Unmarshal(b, &str)
	if err == nil {
		val, ok := CloudletState_CamelValue[util.CamelCase(str)]
		if !ok {
			// may have omitted common prefix
			val, ok = CloudletState_CamelValue["CloudletState"+util.CamelCase(str)]
		}
		if !ok {
			// may be int value instead of enum name
			ival, err := strconv.Atoi(str)
			val = int32(ival)
			if err == nil {
				_, ok = CloudletState_CamelName[val]
			}
		}
		if !ok {
			return errors.New(fmt.Sprintf("No enum value for %s", str))
		}
		*e = CloudletState(val)
		return nil
	}
	var val int32
	err = json.Unmarshal(b, &val)
	if err == nil {
		*e = CloudletState(val)
		return nil
	}
	return fmt.Errorf("No enum value for %v", b)
}

/*
 * This is removed because we do not have enough time in
 * release 3.0 to update the SDK, UI, and documentation for this
 * change. It should be done in 3.1.
func (e CloudletState) MarshalJSON() ([]byte, error) {
	str := proto.EnumName(CloudletState_CamelName, int32(e))
	str = strings.TrimPrefix(str, "CloudletState")
	return json.Marshal(str)
}
*/
var CloudletStateCommonPrefix = "CloudletState"

var MaintenanceStateStrings = []string{
	"NORMAL_OPERATION",
	"MAINTENANCE_START",
	"FAILOVER_REQUESTED",
	"FAILOVER_DONE",
	"FAILOVER_ERROR",
	"MAINTENANCE_START_NO_FAILOVER",
	"CRM_REQUESTED",
	"CRM_UNDER_MAINTENANCE",
	"CRM_ERROR",
	"NORMAL_OPERATION_INIT",
	"UNDER_MAINTENANCE",
}

const (
	MaintenanceStateNORMAL_OPERATION              uint64 = 1 << 0
	MaintenanceStateMAINTENANCE_START             uint64 = 1 << 1
	MaintenanceStateFAILOVER_REQUESTED            uint64 = 1 << 2
	MaintenanceStateFAILOVER_DONE                 uint64 = 1 << 3
	MaintenanceStateFAILOVER_ERROR                uint64 = 1 << 4
	MaintenanceStateMAINTENANCE_START_NO_FAILOVER uint64 = 1 << 5
	MaintenanceStateCRM_REQUESTED                 uint64 = 1 << 6
	MaintenanceStateCRM_UNDER_MAINTENANCE         uint64 = 1 << 7
	MaintenanceStateCRM_ERROR                     uint64 = 1 << 8
	MaintenanceStateNORMAL_OPERATION_INIT         uint64 = 1 << 9
	MaintenanceStateUNDER_MAINTENANCE             uint64 = 1 << 10
)

var MaintenanceState_CamelName = map[int32]string{
	// NORMAL_OPERATION -> NormalOperation
	0: "NormalOperation",
	// MAINTENANCE_START -> MaintenanceStart
	1: "MaintenanceStart",
	// FAILOVER_REQUESTED -> FailoverRequested
	2: "FailoverRequested",
	// FAILOVER_DONE -> FailoverDone
	3: "FailoverDone",
	// FAILOVER_ERROR -> FailoverError
	4: "FailoverError",
	// MAINTENANCE_START_NO_FAILOVER -> MaintenanceStartNoFailover
	5: "MaintenanceStartNoFailover",
	// CRM_REQUESTED -> CrmRequested
	6: "CrmRequested",
	// CRM_UNDER_MAINTENANCE -> CrmUnderMaintenance
	7: "CrmUnderMaintenance",
	// CRM_ERROR -> CrmError
	8: "CrmError",
	// NORMAL_OPERATION_INIT -> NormalOperationInit
	9: "NormalOperationInit",
	// UNDER_MAINTENANCE -> UnderMaintenance
	31: "UnderMaintenance",
}
var MaintenanceState_CamelValue = map[string]int32{
	"NormalOperation":            0,
	"MaintenanceStart":           1,
	"FailoverRequested":          2,
	"FailoverDone":               3,
	"FailoverError":              4,
	"MaintenanceStartNoFailover": 5,
	"CrmRequested":               6,
	"CrmUnderMaintenance":        7,
	"CrmError":                   8,
	"NormalOperationInit":        9,
	"UnderMaintenance":           31,
}

func (e *MaintenanceState) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var str string
	err := unmarshal(&str)
	if err != nil {
		return err
	}
	val, ok := MaintenanceState_CamelValue[util.CamelCase(str)]
	if !ok {
		// may be enum value instead of string
		ival, err := strconv.Atoi(str)
		val = int32(ival)
		if err == nil {
			_, ok = MaintenanceState_CamelName[val]
		}
	}
	if !ok {
		return errors.New(fmt.Sprintf("No enum value for %s", str))
	}
	*e = MaintenanceState(val)
	return nil
}

func (e MaintenanceState) MarshalYAML() (interface{}, error) {
	str := proto.EnumName(MaintenanceState_CamelName, int32(e))
	return str, nil
}

// custom JSON encoding/decoding
func (e *MaintenanceState) UnmarshalJSON(b []byte) error {
	var str string
	err := json.Unmarshal(b, &str)
	if err == nil {
		val, ok := MaintenanceState_CamelValue[util.CamelCase(str)]
		if !ok {
			// may be int value instead of enum name
			ival, err := strconv.Atoi(str)
			val = int32(ival)
			if err == nil {
				_, ok = MaintenanceState_CamelName[val]
			}
		}
		if !ok {
			return errors.New(fmt.Sprintf("No enum value for %s", str))
		}
		*e = MaintenanceState(val)
		return nil
	}
	var val int32
	err = json.Unmarshal(b, &val)
	if err == nil {
		*e = MaintenanceState(val)
		return nil
	}
	return fmt.Errorf("No enum value for %v", b)
}

/*
 * This is removed because we do not have enough time in
 * release 3.0 to update the SDK, UI, and documentation for this
 * change. It should be done in 3.1.
func (e MaintenanceState) MarshalJSON() ([]byte, error) {
	str := proto.EnumName(MaintenanceState_CamelName, int32(e))
	return json.Marshal(str)
}
*/
func (m *AppPort) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Proto != 0 {
		n += 1 + sovAppcommon(uint64(m.Proto))
	}
	if m.InternalPort != 0 {
		n += 1 + sovAppcommon(uint64(m.InternalPort))
	}
	if m.PublicPort != 0 {
		n += 1 + sovAppcommon(uint64(m.PublicPort))
	}
	l = len(m.FqdnPrefix)
	if l > 0 {
		n += 1 + l + sovAppcommon(uint64(l))
	}
	if m.EndPort != 0 {
		n += 1 + sovAppcommon(uint64(m.EndPort))
	}
	if m.Tls {
		n += 2
	}
	if m.Nginx {
		n += 2
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DeviceInfoStatic) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DeviceOs)
	if l > 0 {
		n += 1 + l + sovAppcommon(uint64(l))
	}
	l = len(m.DeviceModel)
	if l > 0 {
		n += 1 + l + sovAppcommon(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *DeviceInfoDynamic) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.DataNetworkType)
	if l > 0 {
		n += 1 + l + sovAppcommon(uint64(l))
	}
	if m.SignalStrength != 0 {
		n += 1 + sovAppcommon(uint64(m.SignalStrength))
	}
	l = len(m.CarrierName)
	if l > 0 {
		n += 1 + l + sovAppcommon(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovAppcommon(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAppcommon(x uint64) (n int) {
	return sovAppcommon(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *AppPort) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAppcommon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: AppPort: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: AppPort: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proto", wireType)
			}
			m.Proto = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppcommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Proto |= LProto(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field InternalPort", wireType)
			}
			m.InternalPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppcommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.InternalPort |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PublicPort", wireType)
			}
			m.PublicPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppcommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PublicPort |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FqdnPrefix", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppcommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAppcommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAppcommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FqdnPrefix = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndPort", wireType)
			}
			m.EndPort = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppcommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndPort |= int32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tls", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppcommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Tls = bool(v != 0)
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Nginx", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppcommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Nginx = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipAppcommon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAppcommon
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAppcommon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeviceInfoStatic) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAppcommon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceInfoStatic: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceInfoStatic: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceOs", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppcommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAppcommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAppcommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceOs = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DeviceModel", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppcommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAppcommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAppcommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DeviceModel = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAppcommon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAppcommon
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAppcommon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *DeviceInfoDynamic) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAppcommon
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: DeviceInfoDynamic: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: DeviceInfoDynamic: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DataNetworkType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppcommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAppcommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAppcommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DataNetworkType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignalStrength", wireType)
			}
			m.SignalStrength = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppcommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignalStrength |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CarrierName", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAppcommon
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAppcommon
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAppcommon
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CarrierName = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAppcommon(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthAppcommon
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthAppcommon
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAppcommon(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAppcommon
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAppcommon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAppcommon
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAppcommon
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAppcommon
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAppcommon
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAppcommon        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAppcommon          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAppcommon = fmt.Errorf("proto: unexpected end of group")
)
