##
##
description: Deploys and starts a system, adds provisioning. Does not stop or cleanup

tests:

- name: deploy and start services 
  actions: [deploy,start,sleep=3]

- name: verify services are running
  actions: [status]

- name: create provisioning
  apifile: "{{datadir}}/appdata_automation.yml"
  actions: [ctrlapi-create,ctrlapi-show]
