apiVersion: v1
kind: Service
metadata:
  labels:
    app: vault
  name: vault
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: vault
    port: 8200
    protocol: TCP
  selector:
    app: vault
  sessionAffinity: None
  type: NodePort
