apiVersion: apps/v1
kind: Deployment
metadata:
  name: crmcentralgcp
  labels:
    app: crmcentralgcp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crmcentralgcp
  template:
    metadata:
      labels:
        app: crmcentralgcp
    spec:
      containers:
      - name: crmcentralgcp
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:latest
        imagePullPolicy: Always
        env:
         - name: PATH
           value: /tmp/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/root/bin
         - name: MEX_CF_USER
           value: mobiledgex.ops@mobiledgex.com
         - name: MEX_CF_KEY
           value: 60632181cb3b7419304ffa820b2d99e292092
         - name: MEX_SSH_KEY
           value: id_rsa_mobiledgex
         - name: MEX_DOCKER_REG_PASS
           value: sandhill
         - name: MEX_DIR
           value: /root/.mobiledgex
         - name: OS_AUTH_URL
           value: NOTHING
         - name: OS_CACERT
           value: NOTHING
         - name: OS_USERNAME
           value: mexadmin
         - name: OS_PASSWORD
           value: NOTHING
         - name: OS_REGION_NAME
           value: RegionOne
         - name: OS_TENANT_NAME
           value: mex
        command:
         - crmserver
        args:
         - "--apiAddr"
         - "0.0.0.0:55091"
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"gcp\"},\"name\":\"centraluscloudlet\"}"
         - "--notifyAddrs"
         - "controller:37001"
         - "--tls"
         - "/root/tls/mex-server.crt"
         - "--d"
         - "mexos"

      imagePullSecrets:
       - name: mexreg-secret

