apiVersion: v1
kind: application
resource: hamedgecloud.telekom.de:5000/v2.0
metadata:
  kind: mex-app-k8s
  name: testapp
  tags: testapp-k8s-tag
  tenant: testtenant
  operator: mex-tdg
spec:
  flags: none
  key: testcluster
  rootlb: hamburg.mex-tdg.mobiledgex.net
  image: registry.mobiledgex.net:5000/mobiledgex/mexexample
  imagetype: ImageTypeDocker
  proxypath: testapp
  flavor: x1.medium
  uri: https://testapp.hamburg.mex-tdg.mobiledgex.net
  ipaccess: IpAccessShared
  kubemanifesttemplate: 
  ports:
  - name: lprotohttp1
    mexproto: LProtoHTTP
    proto: TCP
    internalport: 27272
    publicport: 27272
    publicpath: testappgrpc
  - name: lprotohttp2
    mexproto: LProtoHTTP
    proto: TCP
    internalport: 27273
    publicport: 27273
    publicpath: testapprest
  - name: lprotohttp3
    mexproto: LProtoHTTP
    proto: TCP
    internalport: 27274
    publicport: 27274
    publicpath: testapphttp
  command:
