apiVersion: v1
kind: application
resource: hamedgecloud.telekom.de:5000/v2.0
metadata:
  kind: mex-app-k8s
  name: testapp
  tags: testapp-k8s-tag
  tenant: testtenant
  operator: mex-tdg
spec:
  flags: none
  key: testcluster
  rootlb: hamburg.mex-tdg.mobiledgex.net
  image: registry.mobiledgex.net:5000/mobiledgex/mexexample
  imagetype: ImageTypeDocker
  proxypath: testapp
  portmap: 
  pathmap: /etc:/mexexample
  flavor: x1.medium
  uri: https://testapp.hamburg.mex-tdg.mobiledgex.net
  kubemanifest: http://registry.mobiledgex.net:8080/mobiledgex/testapp.yaml
  accesslayer: L7
