vars:
  - locverurl: "http://127.0.0.1:8888/verifyLocation" 
  - toksrvurl: "http://127.0.0.1:9999/its?followURL%3Dhttps://dme.mobiledgex.net/verifyLoc" 

tlscerts:
- commonname: localserver
  ips:
    - 127.0.0.1
    - 0.0.0.0

locsims:
- name: locsim1
  port: 8888
  locfile: "{{datadir}}/locsim.yml"
  geofile: "{{datadir}}/geocode.dat"
  country: US
  hostname: "127.0.0.1"

toksims:
- name: toksim1
  port: 9999
  hostname: "127.0.0.1"

vaults:
- name: vault
  hostname: "127.0.0.1"

influxs:
- name: influx1
  datadir: /var/tmp/edge-cloud-local-influx/influx1
  httpaddr: "127.0.0.1:8086"
  hostname: "127.0.0.1"

etcds:
- name: etcd1
  datadir: /var/tmp/edge-cloud-local-etcd/etcd1
  peeraddrs: "http://127.0.0.1:30011"
  clientaddrs: "http://127.0.0.1:30001"
  initialcluster: "etcd1=http://127.0.0.1:30011,etcd2=http://127.0.0.1:30012,etcd3=http://127.0.0.1:30013"
  hostname: "127.0.0.1"

- name: etcd2
  datadir: /var/tmp/edge-cloud-local-etcd/etcd2
  peeraddrs: "http://127.0.0.1:30012"
  clientaddrs: "http://127.0.0.1:30002"
  initialcluster: "etcd1=http://127.0.0.1:30011,etcd2=http://127.0.0.1:30012,etcd3=http://127.0.0.1:30013"
  hostname: "127.0.0.1"

- name: etcd3
  datadir: /var/tmp/edge-cloud-local-etcd/etcd3
  peeraddrs: "http://127.0.0.1:30013"
  clientaddrs: "http://127.0.0.1:30003"
  initialcluster: "etcd1=http://127.0.0.1:30011,etcd2=http://127.0.0.1:30012,etcd3=http://127.0.0.1:30013"
  hostname: "127.0.0.1"

controllers:
- name: ctrl1
  etcdaddrs: "http://127.0.0.1:30001,http://127.0.0.1:30002,http://127.0.0.1:30003"
  apiaddr: "0.0.0.0:55001"
  httpaddr: "0.0.0.0:36001"
  notifyaddr: "127.0.0.1:37001"
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

- name: ctrl2
  etcdaddrs: "http://127.0.0.1:30001,http://127.0.0.1:30002,http://127.0.0.1:30003"
  apiaddr: "0.0.0.0:55002"
  httpaddr: "0.0.0.0:36002"
  notifyaddr: "127.0.0.1:37002"
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"


dmes:
- name: dme1
  apiaddr: "0.0.0.0:50051"
  httpaddr: "0.0.0.0:38001"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  locverurl: "{{locverurl}}"
  toksrvurl: "{{toksrvurl}}"
  carrier: TDG
  cloudletkey: '{"operator_key":{"name":"TDG"},"name":"automationBonnCloudlet"}'
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"
  envvars:
    LOCAPI_USER: mexserver
    LOCAPI_PASSWD: eC2835!

crms:
- name: crm1
  apiaddr: "0.0.0.0:55091"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  cloudletkey: '{"operator_key":{"name":"tmus"},"name":"tmocloud-1"}'
  platform: fakecloudlet
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

- name: crm2
  apiaddr: "0.0.0.0:55092"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  cloudletkey: '{"operator_key":{"name":"tmus"},"name":"tmocloud-2"}'
  platform: fakecloudlet
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

- name: crm3
  apiaddr: "0.0.0.0:55093"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  cloudletkey: '{"operator_key":{"name":"tmus"},"name":"tmocloud-3"}'
  platform: fakecloudlet
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

- name: crm4
  apiaddr: "0.0.0.0:55094"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  cloudletkey: '{"operator_key":{"name":"tmus"},"name":"tmocloud-4"}'
  platform: fakecloudlet
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

- name: crm5
  apiaddr: "0.0.0.0:55095"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  cloudletkey: '{"operator_key":{"name":"tmus"},"name":"tmocloud-5"}'
  platform: fakecloudlet
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

- name: crm6
  apiaddr: "0.0.0.0:55096"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  cloudletkey: '{"operator_key":{"name":"tmus"},"name":"tmocloud-6"}'
  platform: fakecloudlet
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

- name: crm7
  apiaddr: "0.0.0.0:55097"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  cloudletkey: '{"operator_key":{"name":"tmus"},"name":"tmocloud-7"}'
  platform: fakecloudlet
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

- name: crm8
  apiaddr: "0.0.0.0:55098"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  cloudletkey: '{"operator_key":{"name":"tmus"},"name":"tmocloud-8"}'
  platform: fakecloudlet
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

- name: crm9
  apiaddr: "0.0.0.0:55099"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  cloudletkey: '{"operator_key":{"name":"tmus"},"name":"tmocloud-9"}'
  platform: fakecloudlet
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

- name: crm10
  apiaddr: "0.0.0.0:55100"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  cloudletkey: '{"operator_key":{"name":"tmus"},"name":"tmocloud-10"}'
  platform: fakecloudlet
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

- name: crm11
  apiaddr: "0.0.0.0:55101"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  cloudletkey: '{"operator_key":{"name":"azure"},"name":"azurecloud-1"}'
  platform: fakecloudlet
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

- name: crm12
  apiaddr: "0.0.0.0:55102"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  cloudletkey: '{"operator_key":{"name":"gcp"},"name":"gcpcloud-1"}'
  platform: fakecloudlet
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

- name: crm13
  apiaddr: "0.0.0.0:55103"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  cloudletkey: '{"operator_key":{"name":"att"},"name":"attcloud-1"}'
  platform: fakecloudlet
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

mcs:
- name: mc1
  addr: "127.0.0.1:9900"
  sqladdr: "127.0.0.1:5432"
  vaultaddr: "http://127.0.0.1:8200"
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    serverkey: "{{tlsoutdir}}/mex-server.key"
    clientcert: "{{tlsoutdir}}/mex-client.crt"
  hostname: "127.0.0.1"

sqls:
- name: sql1
  datadir: /var/tmp/edge-cloud-local-sql/sql1
  httpaddr: "127.0.0.1:5432"
  username: mcuser
  dbname: mcdb
  tls:
    servercert: "{{tlsoutdir}}/mex-server.crt"
    serverkey: "{{tlsoutdir}}/mex-server.key"
  hostname: "127.0.0.1"

