vars:
  - locverurl: "http://127.0.0.1:8888/verifyLocation" 
  - toksrvurl: "http://127.0.0.1:9999/its?followURL%3Dhttps://dme.mobiledgex.net/verifyLoc" 

sampleapps:
- name: mexexample1
  exename: mexexample
  args: 
    - "-debug"
  hostname: "127.0.0.1"
 
locsims:
- name: locsim1
  port: 8888
  locfile: "{{datadir}}/locsim.yml"
  hostname: "127.0.0.1"

toksims:
- name: toksim1
  port: 9999
  hostname: "127.0.0.1"

etcds:
- name: etcd1
  datadir: /var/tmp/edge-cloud-local-etcd/etcd1
  peeraddrs: "http://127.0.0.1:30011"
  clientaddrs: "http://127.0.0.1:30001"
  initialcluster: "etcd1=http://127.0.0.1:30011,etcd2=http://127.0.0.1:30012,etcd3=http://127.0.0.1:30013"
  hostname: "127.0.0.1"

- name: etcd2
  datadir: /var/tmp/edge-cloud-local-etcd/etcd2
  peeraddrs: "http://127.0.0.1:30012"
  clientaddrs: "http://127.0.0.1:30002"
  initialcluster: "etcd1=http://127.0.0.1:30011,etcd2=http://127.0.0.1:30012,etcd3=http://127.0.0.1:30013"
  hostname: "127.0.0.1"

- name: etcd3
  datadir: /var/tmp/edge-cloud-local-etcd/etcd3
  peeraddrs: "http://127.0.0.1:30013"
  clientaddrs: "http://127.0.0.1:30003"
  initialcluster: "etcd1=http://127.0.0.1:30011,etcd2=http://127.0.0.1:30012,etcd3=http://127.0.0.1:30013"
  hostname: "127.0.0.1"

controllers:
- name: ctrl1
  etcdaddrs: "http://127.0.0.1:30001,http://127.0.0.1:30002,http://127.0.0.1:30003"
  apiaddr: "0.0.0.0:55001"
  httpaddr: "0.0.0.0:36001"
  notifyaddr: "127.0.0.1:37001"
  shorttimeouts: true
  hostname: "127.0.0.1"

dmes:
- name: dme1
  apiaddr: "0.0.0.0:50051"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  locverurl: "{{locverurl}}"
  toksrvurl: "{{toksrvurl}}"
  carrier: GDDT
  cloudletkey: '{"operator_key":{"name":"dmuus"},"name":"tmocloud-1"}'
  hostname: "127.0.0.1"

  
crms:
- name: crm1
  apiaddr: "0.0.0.0:55091"
  notifyaddrs: "127.0.0.1:37001,127.0.0.1:37002"
  cloudletkey: '{"operator_key":{"name":"dmuus"},"name":"tmocloud-1"}'
  hostname: "127.0.0.1"

