apiVersion: v1
kind: Service
metadata:
  labels:
    app: controller
  name: controller
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
   - port: 55001
     protocol: TCP
     targetPort: 55001
  selector:
    app: controller
  sessionAffinity: None
  type: LoadBalancer
