apiVersion: apps/v1
kind: Deployment
metadata:
  name: crm
  labels:
    app: crm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: crm
  template:
    metadata:
      labels:
        app: crm
    spec:
      containers:
      - name: crm
        image: registry.mobiledgex.net:5000/mobiledgex/edge-cloud:latest
        command:
         - "crmserver"
         - "--apiAddr"
         - "0.0.0.0:50091"
         - "--cloudletKey"
         - "{\"operator_key\":{\"name\":\"TDG\"},\"name\":\"Bonn\"}"
         - "--notifyAddrs"
         - "controller:37001"
         
      imagePullSecrets:
       - name: mexreg-secret 

